// 360 daily fortunes — 30 per Western zodiac sign.
// Keyed by English sign name (used as the canonical key across all locales).

const FORTUNES_EN: Record<string, string[]> = {
  Aries: [
    "A burst of initiative arrives today — trust it. The project or conversation you've been putting off is ready to begin. Strike while your energy is high.",
    "Your competitive edge sharpens this morning. Channel it into something constructive and you'll surprise even yourself with what you accomplish.",
    "Slow down before you leap today. Your instincts are reliable, but a single moment of reflection will make your next move twice as effective.",
    "Leadership comes naturally to you, and today someone is watching how you handle a challenge. Let your actions speak louder than your plans.",
    "Physical energy is your currency today — spend it wisely. A walk, a workout, or even an energetic conversation can reset everything.",
    "A new beginning is closer than it appears. The door you've been waiting on may open with a push, not a knock.",
    "Impatience is your shadow today. Notice when it's driving you and ask whether speed or precision is what this moment actually needs.",
    "Your directness will be appreciated more than you expect today. Say what you mean — the people around you are ready to hear it.",
    "Something competitive stirs in you. Use that fire to motivate rather than intimidate, and you'll bring others with you rather than past them.",
    "Rest is strategy today, not surrender. Even the boldest warrior knows when to recharge before the next advance.",
    "An opportunity arrives disguised as an obstacle. Aries energy excels at finding the gap — look for the way through, not around.",
    "Your enthusiasm is contagious today. Share it freely and watch how the people around you rise to match your energy.",
    "A goal you set weeks ago is within reach. The final push requires less than you think — mostly just showing up.",
    "Watch for a moment of conflict today. Your instinct is to win; the wiser move may be to listen first and respond second.",
    "Courage isn't the absence of doubt — it's acting in spite of it. Today's circumstances are asking exactly that of you.",
    "Your appetite for the new is an asset. Follow a curiosity that's been nagging you and see where the thread leads.",
    "A relationship benefits from your honesty today. Be direct but warm — your words carry more weight than you realize.",
    "Today is a day for beginnings. Write the first line, make the first call, take the first step. Momentum follows action.",
    "Your energy peaks early today. Front-load your most demanding tasks and leave the afternoon for the lighter ones.",
    "Someone may challenge your authority or ideas today. Respond with confidence, not defensiveness — your track record speaks for itself.",
    "Creativity and action align today. If you have an idea that's been waiting, give it form — even a rough draft counts.",
    "Generosity serves you well today. Sharing your knowledge or time costs you little and builds something lasting.",
    "A problem you've been attacking head-on may need a different approach. Step back, look at the full picture, then go again.",
    "Your ruling planet Mars gives you endurance today. Push through the middle of a task — the finish line is closer than it feels.",
    "Independent by nature, you sometimes forget that collaboration can amplify your results. Let someone help today — it's not weakness.",
    "Spontaneity is your friend today. The best outcome may come from the unplanned detour, not the carefully plotted route.",
    "A small act of bravery — a message sent, a fear named, a risk taken — will ripple forward in ways you won't immediately see.",
    "Reflect on what you've started recently. Which ventures deserve more fuel? Direct your fire where it will actually burn bright.",
    "Today favors the bold but rewards the prepared. Have your facts ready, your confidence natural, and your timing patient.",
    "The day ends better than it begins. Push through any morning friction and trust that the afternoon holds something worth the wait.",
  ],

  Taurus: [
    "Comfort is your birthright today, Taurus. Create the environment that helps you think clearly — a clean desk, a good meal, the right music — and your productivity will follow naturally.",
    "Patience is being tested, but your famous endurance is exactly what this situation needs. The slow and steady path is still the right one.",
    "A creative impulse connected to beauty or aesthetics is worth following today. Your eye for quality makes you a natural curator — trust that.",
    "Financial matters deserve a second look. A small adjustment now — a subscription cancelled, a budget reviewed — compounds into real savings over time.",
    "Loyalty defines you, and today someone in your circle recognizes it. A quiet word of appreciation is coming; receive it graciously.",
    "Your senses are heightened today. A meal shared, a garden visited, a piece of music allowed to play through completely — these are not luxuries, they are fuel.",
    "Stubbornness serves you when your convictions are right. Today, pause and check: is what you're holding onto wisdom or habit?",
    "Security matters to you, and that's healthy. Today, take one practical step — however small — toward a goal that makes you feel more stable.",
    "Venus, your ruling planet, activates your charm today. Social interactions go smoothly, and a genuine compliment you give will be remembered.",
    "Slow mornings lead to steady days. Don't rush the start — let your pace build naturally and you'll outperform those who burned bright at dawn.",
    "A conversation about money or resources with someone you trust is timely. Shared perspectives help you see options you've been missing.",
    "Your reliability is your reputation, and it's working in your favor right now. An opportunity arriving soon is partly because of that track record.",
    "Beauty in small things — a morning light, a hand-written note — carries extra meaning today. Let yourself be moved by it.",
    "A project that requires sustained effort is exactly suited to your nature. Begin the next chapter of it today without waiting for perfect conditions.",
    "You may feel resistance to change today, and that's valid to name. But ask: what is the cost of staying still compared to the cost of moving?",
    "Physical comfort is tied to your mood in ways you sometimes overlook. A nap, a stretch, a proper meal — treat your body well and your outlook shifts.",
    "Someone may mistake your calmness for indifference today. A brief expression of what you're actually thinking will clear up a misunderstanding before it grows.",
    "Possessiveness can masquerade as care. Today, notice if you're holding on to something — or someone — out of love or out of fear.",
    "A long-term goal gets a boost today. The work you've put in quietly over weeks is beginning to compound into something visible.",
    "Your taste and judgment are reliable guides. When everyone else is uncertain, your grounded instincts often point to the right answer.",
    "Nature restores you. If you can spend even fifteen minutes outside today, do it. Your body knows what your mind sometimes forgets.",
    "An old friendship or connection resurfaces. Taurus energy keeps bonds alive — reach out and find that the warmth never really faded.",
    "Practicality is your superpower. Before getting swept up in an exciting idea, ask the basic questions: What does this actually cost? What does it actually require?",
    "Today is well-suited to tasks that require concentration and craft. Put on something you love listening to and do the work that requires your full attention.",
    "Generosity flows easily from you today. A gift of time, food, or genuine attention means more coming from you than from almost anyone else.",
    "Trust your rhythm. You work in longer cycles than most people — don't judge today's progress by someone else's pace.",
    "A small but meaningful pleasure is waiting in your day — notice it when it arrives and let yourself enjoy it fully instead of rushing past.",
    "Your values are your compass. When a decision feels complicated, return to the question: what do I actually believe matters here?",
    "Venus brings warmth to your closest relationships today. A moment of undivided attention offered to someone you love lands beautifully.",
    "The tortoise wins not by speed but by showing up without stopping. Today is just one more step on a journey that's already further along than you sometimes acknowledge.",
  ],

  Gemini: [
    "Your mind is running fast today, Gemini — give it a worthy problem to solve and watch what emerges. Boredom is your only real enemy.",
    "A conversation you didn't plan will be the most interesting thing that happens today. Say yes to the unexpected exchange.",
    "Two ideas you've been holding separately suddenly connect. Write it down immediately — the synthesis is the insight.",
    "Communication is your strength and today it's especially sharp. A message, email, or presentation lands exactly as intended.",
    "Mercury, your ruling planet, sharpens your wit today. Use it to delight rather than deflect — the people who get your humor are worth finding.",
    "Your adaptability is being called on. A situation that shifts unexpectedly is actually better suited to your skills than the original plan was.",
    "Curiosity takes you somewhere useful today. Follow the thread of a question that's been sitting in the back of your mind — it leads somewhere worthwhile.",
    "A restless morning gives way to a productive afternoon. Let the ideas circulate in the early hours; the clarity will arrive by midday.",
    "Multitasking is your natural mode, but today one task deserves your singular focus. The result will surprise you.",
    "Something you read, hear, or watch sparks an idea worth keeping. Keep something nearby to capture it — your best thoughts move fast.",
    "A relationship benefits from a real conversation today — not the quick check-in, but the actual one. Make time for depth.",
    "Your versatility opens a door today that would stay closed for less adaptable people. Walk through it without overthinking.",
    "Indecision visits you today, as it sometimes does. Pick the option that excites you more — either path is workable; forward momentum is what matters.",
    "Teach something today, even informally. Explaining what you know clarifies it for yourself as much as it helps the listener.",
    "Social energy is high and connections are easy. An introduction made today could become important in ways neither of you expects.",
    "Your tendency to see multiple sides is a gift, but commit when the time comes. A half-made decision is harder to live with than a made one.",
    "Light-heartedness is underrated. Don't let anyone — including yourself — make you feel like playfulness is less serious than seriousness.",
    "A short trip, errand, or change of environment resets your thinking completely. Even twenty minutes somewhere different unlocks a fresh perspective.",
    "You're processing more than you're showing today. Give yourself a quiet hour before bed to let the day's inputs settle.",
    "Writing clarifies what talking only circulates. Spend ten minutes putting your current thoughts on paper — you'll know more about yourself afterward.",
    "Your charm is working in your favor today. People want to help you — let them.",
    "Scattered energy can be redirected rather than suppressed. Write a three-item priority list and start with the most interesting one.",
    "A forgotten idea or project deserves a second look. What seemed complicated then may be surprisingly approachable now.",
    "Your ability to connect different people is valuable. An introduction or recommendation you make today serves everyone involved.",
    "Nervousness and excitement feel similar in the body. What you're feeling before something new could just as easily be the latter.",
    "Language matters today — the words you choose carry extra weight. Be precise with meaning and generous with tone.",
    "Boredom is your signal that growth is needed. If today feels flat, ask: what would actually challenge me right now?",
    "A twin impulse — to stay and to go, to speak and to listen — resolves when you pick one and commit. Trust the first instinct.",
    "Information arrives from an unexpected source. Something overheard, glimpsed, or casually shared turns out to be exactly what you needed to know.",
    "Your mind is a garden, not a machine. Water it with curiosity, give it variety, and don't be surprised when beautiful things grow in the margins.",
  ],

  Cancer: [
    "Your intuition is clearest when you're still. Take five minutes this morning before the noise begins — what you sense in that quiet is worth trusting.",
    "Someone in your life needs exactly what you're naturally good at: to feel truly heard. Offer that today and the gift returns to you in ways you don't expect.",
    "The home is your sanctuary, and something about your space is asking for attention. A small change — rearranging, clearing, or adding something — improves your whole week.",
    "A memory surfaces today that carries both warmth and ache. Let yourself feel it without judgment — it's part of how you stay connected to what matters.",
    "Your capacity to care is remarkable, but today check that you're including yourself in that circle of care. You cannot pour from an empty vessel.",
    "The Moon, your ruling planet, amplifies emotion today. This is a feature, not a bug — your feelings are data. What are they telling you?",
    "A creative project connected to home, family, or personal history is waiting. Even twenty minutes of attention given to it moves something forward.",
    "Protectiveness rises in you today, perhaps toward someone younger, newer, or more vulnerable. Trust that instinct — your shelter is real.",
    "A conversation that feels risky to start is actually ready to be had. Your sensitivity helps you say hard things in ways that heal rather than harm.",
    "Nostalgia visits you today, not to keep you stuck but to remind you of what you've built. You've come further than you sometimes remember.",
    "Financial security and emotional security are linked for you — address one and the other often improves. A small practical step today eases both.",
    "Your empathy is a strength, but absorbing others' emotions without a filter exhausts you. Notice whose feelings you're carrying and gently set them down.",
    "Creativity flows from feeling today. Don't wait for inspiration — begin from wherever your emotions actually are, and the work will be honest.",
    "Cooking, gardening, or any act of nurturing creation restores you. Schedule it deliberately today rather than hoping it fits in.",
    "A relationship with a family member is ready for a gentle repair. You know what to say — the timing is better than you think.",
    "Your loyalty runs deep and long. Today you may see evidence that someone you've supported has grown in ways your investment helped make possible.",
    "Vulnerability is not your enemy — performed strength is. Let someone in just a little further today and discover what trust actually feels like.",
    "Something you've been protecting doesn't need to be protected anymore. The shell that kept you safe has become the thing keeping you small.",
    "Dreams carry information for you in ways that are worth taking seriously. What showed up last night may be a message worth sitting with.",
    "Your care for others is endless, but grief, frustration, or worry sometimes dresses up as busy-ness. Slow down enough to notice what you're actually feeling.",
    "An act of domestic creativity — cooking something new, making something with your hands — satisfies a need for expression that nothing else quite does.",
    "A friend reaches out today. Accept the invitation, even if your first instinct is to say you're too busy. Connection replenishes you.",
    "Boundaries set from love, not fear, are sustainable. Today is a good day to articulate — clearly but kindly — what you need from someone close.",
    "Children, animals, or anyone who needs a gentle hand are drawn to your energy today. Let yourself be fully present for them.",
    "Security isn't something you find — it's something you build. A small step taken today toward a more stable foundation is exactly the right pace.",
    "Your inner world is rich and sometimes overwhelming. Writing, drawing, or simply sitting quietly gives the emotion somewhere to land.",
    "A long-standing fear about change may relax slightly today when you see that something you were worried about is going better than expected.",
    "The people you've chosen as family — blood or otherwise — deserve to know they matter to you. Say it out loud today. It won't go unsaid twice.",
    "Intuition and logic both have a role today. Trust the gut read but verify the details before committing. You'll find they agree more often than not.",
    "Rest and restoration are productive acts for you — not indulgences. What your body and emotions need tonight, give them without guilt.",
  ],

  Leo: [
    "The spotlight finds you today, Leo — let it. Your presence genuinely lifts the energy in a room, and this is not the day to shrink from that.",
    "Creativity is your oxygen, and something new wants to be made. Give an hour today to whatever form of making brings you most alive.",
    "Your generosity is one of your greatest gifts. An opportunity to give — your time, your platform, your encouragement — arrives today. Take it.",
    "Pride can protect or isolate depending on how you wear it. Today, ask: is this confidence serving me, or keeping me from something I actually need?",
    "The Sun, your ruling planet, is behind everything you initiate today. Start something. Announce something. Commit to something. The energy is there.",
    "Loyalty runs deep in you, and a friend needs that today — not advice, just your steadfast presence. Be there without needing to fix anything.",
    "Recognition for something you did weeks or months ago arrives today. Accept it fully — you earned it and deflecting doesn't serve anyone.",
    "Drama in the environment is best addressed with calm authority rather than matching the intensity. Your centeredness is the most powerful thing in the room.",
    "Your playfulness is one of your most underrated traits. Today is a day to let it out — laughter, creativity, and fun are not frivolous, they're your nature.",
    "A creative project at the halfway point needs your confidence to finish it. The doubt you're feeling is normal; the work is better than you think.",
    "Someone younger or less experienced needs your mentorship. Your willingness to share what you know is a form of leadership that matters more than you realize.",
    "Your warmth reaches someone who's been going through a cold stretch. A simple, generous act today means more than you know.",
    "Ambition stirs today. A goal you'd set aside comes back to mind — this time with a clearer sense of how to approach it.",
    "Vanity and self-respect are different things. One feeds on others' approval; the other doesn't need it. Today you're being called to know the difference.",
    "Collaboration shines when you're in it. Share the stage today and you'll find that the recognition is actually larger for everyone involved.",
    "A performance — literal or metaphorical — goes well today. You've prepared more than you think; trust your instincts in the moment.",
    "Children, animals, or playful spirits seek you out today. Accept the invitation to be less serious than usual. Joy is a legitimate priority.",
    "Your instinct to protect the people you love is strong today. Channel it into action — practical support speaks louder than worry.",
    "Boredom signals that you're ready for a bigger challenge. If today feels too small, it's because you are.",
    "A romantic gesture — spontaneous, heartfelt, unplanned — creates a memory today that outlasts anything scheduled.",
    "Leadership isn't always loud. Today, lead by listening first and speaking second. The room will follow someone who understands it.",
    "Your aesthetic instincts are sharp today. Trust them in creative decisions, interior choices, or anything where taste is the deciding factor.",
    "Something you're creating deserves to be seen. Share it — even in a small way. Art kept private serves no one.",
    "Jealousy, if it visits, is a compass pointing toward something you want. Don't suppress it; translate it into direction.",
    "A compliment you give today lands with unusual depth. You have a way of naming what's true in people — use that gift.",
    "Rest is not defeat. Even lions lie in the shade. Today, what kind of rest restores your full strength?",
    "Your passion for something is contagious in the best possible way. The person you share it with today will catch the flame.",
    "An old dream resurfaces — smaller now that you've grown past the fear of it. It may be the right time to finally give it life.",
    "Your best self shows up when you feel seen, so today spend time with people who actually see you. Anything less is wasting your energy.",
    "Today ends with something to be genuinely proud of. It may be small by the world's standards — it isn't by yours, and yours is the one that matters.",
  ],

  Virgo: [
    "Your eye for detail catches something today that others missed entirely. Trust that observation — it changes the outcome significantly.",
    "Service is meaningful to you, and a genuine opportunity to help arrives today. Give it fully, without keeping score — this is the kind of help that sustains you.",
    "The system you've been meaning to improve is ready to be improved. A small adjustment to how you work or organize saves significant time over weeks.",
    "Perfectionism is a useful tool and an exhausting master. Today, ask: what's the standard this actually requires, and what am I holding to standards it doesn't need?",
    "Mercury, your ruling planet, sharpens your analysis today. A complex situation that's been hard to read becomes legible — you see what's actually happening.",
    "Health habits that have slipped deserve a gentle reset. One small correction today — not a drastic overhaul — starts the momentum in the right direction.",
    "Your practical nature solves what others philosophize about. Someone around you has a real problem — you can see the solution already.",
    "Attention to craft is what separates good from excellent. Today you have the focus to bring something from one to the other.",
    "Worry is a form of thinking that doesn't complete itself. When the loop starts, write down what you're actually concerned about and what, specifically, you can do about it.",
    "Your helpfulness is deeply genuine, which is why it's also sometimes depleting. Today, offer one generous act and then protect the rest of your energy.",
    "An analysis you've been doing quietly on a situation is correct. Trust your conclusions and act on them — the data you've gathered is solid.",
    "Humility and self-deprecation are different things. You can be modest about your knowledge while still trusting your expertise. Today, trust it.",
    "A creative project benefits from your editing instincts. Sometimes the most creative act is knowing what to remove.",
    "Your body is communicating something today — a tightness, a tiredness, a signal you've been ignoring. Listen to it before it has to get louder.",
    "Criticism offered with care is a gift. If someone has earned your honest feedback today, give it — but lead with what's working.",
    "Organization is therapeutic for you. If the day feels unmanageable, spend ten minutes creating structure — a list, a plan, a clear priority — and watch your anxiety drop.",
    "Something you take for granted about your own competence is genuinely exceptional. Let someone remind you of it today without arguing.",
    "Discernment is one of your strongest qualities. You know the difference between what's worth your time and what isn't — apply that standard today.",
    "A relationship benefits from your clarity. You can name what's working and what isn't without cruelty — that's a rare skill. Use it.",
    "Routine is not the enemy of creativity — for you, it's the container that makes creativity possible. Protect your best routines today.",
    "Something small done with extraordinary care today — a message, a meal, a detail in a project — demonstrates a kind of excellence that accumulates.",
    "Your inner critic is useful up to a point. Notice when it crosses from helping you improve to simply exhausting you — and tell it firmly to rest.",
    "A practical problem that seemed stuck becomes solvable today. The missing piece was a conversation you haven't had yet — have it.",
    "Your capacity for sustained work is remarkable. A project that requires deep focus is exactly suited to today's energy — set aside the time and go in.",
    "You see what others overlook: the flaw in the plan, the gap in the argument, the possibility in the problem. Today, share that perspective.",
    "Neatness and clarity in your environment translate directly to neatness and clarity in your thinking. If one is off, address it.",
    "Someone needs the kind of methodical, thoughtful help that you give better than almost anyone. Say yes.",
    "Analysis without action is a kind of procrastination. You've gathered enough information — the next step is to begin.",
    "A wellness habit you've been meaning to start is ready to begin. Not next week, not when conditions are perfect — today, one small step.",
    "At the end of today, let yourself acknowledge what you got right. The standard you hold yourself to is high — meeting it, even partially, deserves recognition.",
  ],

  Libra: [
    "Balance is both your gift and your practice, Libra. Notice where your life is tilting today — not to judge it, but to gently adjust.",
    "Your diplomatic instincts are exactly what a situation needs right now. Step in where others are avoiding — you know how to make both sides feel heard.",
    "Beauty nourishes you in ways that go beyond aesthetics. Time spent with something — or someone — genuinely beautiful restores your equilibrium.",
    "A decision you've been avoiding is ready to be made. Gather the last bit of information you need, then commit. A made decision, even imperfectly, is healthier than perpetual weighing.",
    "Venus, your ruling planet, activates your charm and grace today. Social situations flow easily — you're at your most magnetic in a quiet, elegant way.",
    "Justice matters to you deeply. Today you may witness something that's not quite right and you'll have to decide: is this the moment to say something?",
    "A creative collaboration works beautifully today. Your sense of harmony makes you an ideal partner in any joint creative effort.",
    "Relationships thrive on attention, and today one of yours deserves yours. A focused, undistracted hour with someone you care about restores something in both of you.",
    "Your tendency to see every side can be a gift — use it to understand, not to avoid choosing. At the end of the day, choose.",
    "Peace at any price is not real peace. If you've been keeping quiet about something important to avoid conflict, today offers a gentle opening to speak.",
    "Aesthetic choices made today — in your space, your appearance, your creative work — will satisfy you in ways that last longer than you expect.",
    "An unfair situation that you've been monitoring is shifting. Patience and integrity together are more powerful than reaction.",
    "Harmony in your home environment influences everything else. A small effort to make your space more beautiful or ordered pays surprising dividends today.",
    "Compromise is an art, and you practice it better than most. Today, however, check that the compromise still includes your actual needs.",
    "Someone needs your honest assessment today, not your measured one. You can be kind and direct at the same time — Libra does this better than any other sign.",
    "Social grace is effortless today. You're able to put people at ease without even trying — a gift that makes more difference than you know.",
    "A partnership — personal or professional — is ready to move to a new level. The conversation that initiates it is simpler than you've been anticipating.",
    "Your sense of fairness is a compass. When something feels wrong today — in a system, a relationship, a decision — that instinct is worth listening to.",
    "Indecision sometimes hides a deeper truth: you already know what you want, but you're afraid of what choosing it will mean. Today, be brave about knowing.",
    "Art, music, poetry, or any form of beauty that moves you is medicine today. Schedule it deliberately, not as a reward for when everything else is done.",
    "A disagreement is best handled through curiosity rather than persuasion today. Ask questions you genuinely don't know the answers to.",
    "Your natural inclination toward everyone getting along is admirable but not always realistic. Today, let someone else navigate the tension while you simply observe.",
    "A decision made from values — not from what you think others want — has a different quality to it. What do you actually want here?",
    "Grace under pressure is a Libra specialty. A situation today that feels loaded will benefit from exactly the calm, measured energy you bring.",
    "Connections made today carry extra weight. An introduction, a conversation, a moment of genuine meeting — these matter more than they appear.",
    "Your appreciation for quality over quantity applies to time as much as anything else. A shorter, more meaningful day beats a longer, scattered one.",
    "An imbalance you've been tolerating — in a relationship, a workload, a situation — is ready to be named and addressed. The conversation is overdue.",
    "Creativity flows when your mind is settled. Take a walk, listen to something beautiful, or spend time in a space that calms you before you begin.",
    "You carry people's perspectives with care. Today, someone trusts you with something vulnerable — hold it gently, respond thoughtfully.",
    "At the end of today, something will feel more settled than it did at the start. Not because the world changed — because you found your footing within it.",
  ],

  Scorpio: [
    "Your perception cuts to what's real today, Scorpio. Trust what you see beneath the surface — the undercurrent you've detected is worth following.",
    "A transformation is underway, even if it's not yet visible from the outside. Trust the process happening in the depths — the metamorphosis is real.",
    "Intensity is your mode, and today it's an asset. Whatever you focus on receives the full force of your attention — choose wisely.",
    "A secret you've been keeping — even from yourself — wants to be acknowledged today. The truth you already know is ready to be lived with.",
    "Pluto, your ruling planet, deepens everything you touch today. A conversation that begins one way ends somewhere neither person expected — and better for it.",
    "Your capacity for loyalty runs to great depths. Someone in your circle has earned more trust than you've given them — today is the day to offer it.",
    "Passion directed well creates. Passion directed without aim burns. Today, be intentional about what you're pouring yourself into.",
    "Something ending today is making space for something that couldn't have arrived while the old thing was still there. Let it go.",
    "Your instincts about someone are accurate. You don't always need to act on them immediately — sitting with what you perceive gives you an advantage.",
    "A desire that's been lurking at the edges of your awareness deserves honest acknowledgment. What do you actually want — not what you're supposed to want?",
    "Power dynamics interest you, but watch for the difference between understanding them and being controlled by them. You're most powerful when you're free.",
    "A healing — of a relationship, a wound, a long-held tension — becomes possible today. You don't have to rush it, but you can open the door.",
    "Research, investigation, or deep reading feeds something in you that surface-level stimulation cannot. Give your mind something worth digging into.",
    "You sense what's changing before others name it. Use that perception to prepare rather than to dread.",
    "Vulnerability is not your natural posture, but today it's what creates the connection you actually want. Let someone see more of you than you usually allow.",
    "A grudge that's been quietly running in the background is costing you energy you could be using for something else. Release is not forgiveness of them — it's freedom for you.",
    "Your magnetic presence draws people in today without effort. Be conscious of who you're inviting into your orbit.",
    "Something you've been investigating — a situation, a person, an idea — becomes clearer today. The picture assembles itself if you keep looking.",
    "Transformation is rarely comfortable, but it's always your most natural terrain. You know how to survive reinvention — you've done it before.",
    "A financial matter deserves close attention today. Your instincts about where something doesn't add up are worth following through on.",
    "The silence you hold can be either wisdom or distance. Today, notice which one it is — and if it's distance, close it.",
    "Your depth of feeling is one of your greatest gifts, even when it's heavy. What you feel, you feel completely — don't ask yourself to feel less.",
    "Trust and control are in tension today. You can't fully have both — which one actually matters more to you in this situation?",
    "Something dark that you've been looking at honestly is losing some of its power over you. Understanding it was the first step. This is the second.",
    "Sexuality, creativity, and power are all expressions of the same fundamental energy in you. Today, channel it consciously.",
    "A dream or recurring image has been trying to tell you something. Scorpio's unconscious is rarely random — what symbol has been showing up?",
    "Your capacity for regeneration is extraordinary. What you've been through would have broken someone with less depth. You rebuilt — and you're still building.",
    "Obsession and passion feel similar from the inside but produce different outcomes. Check: is this something that's consuming you or something that's fueling you?",
    "The thing you protect most fiercely sometimes needs to be released precisely because you love it so much. Today, consider what holding on is actually protecting.",
    "At the end of this day, something is different in you — even if no one else can see it. Scorpio's changes happen from the inside out, and they're permanent.",
  ],

  Sagittarius: [
    "The horizon is always calling you, Sagittarius, and today it has something specific to say. Follow the curiosity that points you outward — literally or through a book, a conversation, a new perspective.",
    "Optimism is your native tongue, and today it's contagious. Share it freely — your willingness to believe things can be better inspires people more than they admit.",
    "An adventure is ready to begin, even if it starts as a small departure from routine. Say yes to the thing that breaks the pattern.",
    "Your philosophical mind is wrestling with a big question today. Let it. The searching is as valuable as the answer — maybe more so.",
    "Jupiter, your ruling planet, expands whatever you touch today. Start something, and watch it grow larger and faster than you expected.",
    "Freedom is your core need, and today you may feel it constrained. Name what's limiting you — and then decide whether the limit is real or perceived.",
    "A teacher arrives in an unexpected form today — a stranger's offhand remark, a book falling open to a certain page, a challenge that contains a lesson.",
    "Your honesty is rare and sometimes startling. Today, find the moment where it's genuinely helpful — and share what you see without editing yourself into vagueness.",
    "A plan that requires flexibility plays to your strengths. Rigid structures frustrate you; open-ended journeys are where you thrive.",
    "Travel — even of the armchair variety — feeds something in you that nothing else does. Explore somewhere today, even from your desk.",
    "Your enthusiasm for ideas is a gift to the people around you. The thing you're most excited about right now is worth talking about.",
    "A risk that's been sitting on your mental shelf is ready to be taken. Not recklessly — but with the knowledge that safety and growth rarely coexist.",
    "Someone needs to hear that things will be okay — and they need to hear it from you, because you say it like you mean it. Because you do.",
    "Your love of learning doesn't require a formal structure. Today's lesson may come from a video, a walk, a dinner conversation — stay open.",
    "The question is more valuable than the answer today. Ask the thing you've been afraid to ask — of yourself or of someone else — and see what comes back.",
    "Your global perspective helps you see a local situation with unusual clarity. Zoom out on a problem that's felt too close and watch it become solvable.",
    "Commitment and freedom feel like opposites to you, but the deepest adventures require both. What are you willing to commit to in order to go further?",
    "A belief you've held for a long time may be ready to evolve. A Sagittarius who stops questioning is a Sagittarius who's stopped growing.",
    "Your physical energy needs an outlet today. Movement — a walk, a run, a spontaneous detour — is not optional, it's maintenance.",
    "Generosity comes naturally to you, and today it flows especially freely. Give what you have — wisdom, laughter, or resources — and don't count it.",
    "A lucky convergence is building today. Three things that seemed unrelated are about to connect in a way that opens a door.",
    "You're allergic to pretense, and today someone's authenticity is refreshing in a way you didn't expect. Spend more time with people who are real.",
    "Something you've always wanted to experience is closer to being possible than you've been assuming. What first step could you take today?",
    "Teaching and learning are the same act seen from different directions. What you share today teaches you something about what you actually know.",
    "Your ruling planet Jupiter governs luck, and today you're in its stream. Reach a little farther than you think you can — the distance is shorter than it looks.",
    "Restlessness is a signal, not a flaw. What is yours pointing toward? It's trying to take you somewhere.",
    "A spiritual or philosophical conversation finds you today — and something said shifts your perspective in a small but lasting way.",
    "What's the biggest thing you could possibly do with what you have right now? Today, take one step toward that answer.",
    "Laughter is underrated as medicine. The day that includes genuine, helpless laughter is a day that has gone right.",
    "You came here to seek, to find, and to keep seeking. Today simply confirms that the journey is exactly what it was supposed to be.",
  ],

  Capricorn: [
    "Your ambition is not arrogance, Capricorn — it's a form of faith in what's possible. Today, act from that faith.",
    "Saturn, your ruling planet, rewards the patient and the persistent. The progress you've made — even the parts invisible from outside — is real and accumulating.",
    "A goal that once seemed impossibly distant is now simply a matter of continued execution. Keep going exactly as you have been.",
    "Responsibility is natural to you, but even the most capable person has limits. Delegate something today that doesn't require you specifically.",
    "A practical problem yields to a practical solution today — not a complicated one. The simplest answer is usually the right one.",
    "Your reputation for reliability is opening a door right now. An opportunity arriving this week is partly because people know they can count on you.",
    "Discipline is your most powerful tool and also your most recognizable trait. Today it's working invisibly in your favor — in ways that will be visible soon.",
    "Status matters to you, and there's no shame in that. The question today is: is what you're pursuing genuinely aligned with what you value, or what you think you're supposed to want?",
    "A financial decision can be made with more confidence than you're currently feeling. You have the information — trust your analysis.",
    "Your sense of humor is drier and sharper than people expect. Today, let it out. You're funnier than your seriousness lets people see.",
    "Leadership by example is your strongest suit. Someone is watching how you handle a difficult situation and learning something they'll carry forward.",
    "Time is your relationship, not your enemy. A long-term investment — of effort, focus, or resources — makes more sense today than any shortcut.",
    "A conversation about your future — with a mentor, a trusted colleague, or simply yourself — clarifies what you're building and why.",
    "Perfectionism in Capricorn often signals that you care, not that you're afraid. Today, check which one is running the show.",
    "Something slow-built is beginning to show results. The accumulation of consistent effort has a compound effect — you're in that phase now.",
    "Work ethic is not a substitute for joy. Today, find at least one moment where what you're doing aligns what you have to do with what you want to do.",
    "Your elder or mentor energy is being asked for today. Someone newer in their journey will benefit from exactly what you've already learned.",
    "The mountain you're climbing is yours. Don't compare your altitude to anyone else's — they're on a different mountain entirely.",
    "A setback is a data point, not a verdict. Reassess, adjust, continue. This is the Capricorn method, and it works.",
    "Structure creates freedom. The systems you build today are the things that give you space tomorrow — invest the time.",
    "Your patience is extraordinary by any standard. Today it's being exercised in a situation that genuinely rewards it — hold your position.",
    "A career move or professional opportunity is ready to be considered seriously. Gather the information, run the numbers, and trust your conclusions.",
    "Home and foundation matter to you, and something about yours is ready for attention — either literally or in terms of the relationships that constitute it.",
    "Recognition for something you've built over a long time is on its way. You've been too close to it to see the magnitude of what you've created.",
    "Earth sign energy grounds everything today. Your practical nature is exactly the stabilizing force that a chaotic situation needs.",
    "Rest is not a reward for when the work is done — the work is never done. Rest is maintenance. Schedule it.",
    "Your inner compass toward what's real and what's not is reliable. When something feels hollow or performative today, trust that read.",
    "A dream that used to feel impossible is beginning to look more like a plan. The difference is that now you can see the steps.",
    "Integrity in small things — following through on a minor commitment, being precise with a small detail — compounds into a reputation that opens large doors.",
    "The long view is your natural perspective. What seems urgent today will be irrelevant in five years. What you do quietly today will matter in twenty.",
  ],

  Aquarius: [
    "Your mind moves differently than the people around you, Aquarius, and today that difference solves something no one else saw coming.",
    "A cause or community that matters to you is asking for your involvement. Your vision for what's possible is needed — don't hold it back.",
    "Innovation is your natural language. Today's problem has a solution that nobody's tried yet — and you're in a unique position to see it.",
    "Uranus, your ruling planet, sparks the unexpected today. Something surprises you — and the surprise turns out to be exactly what you needed.",
    "Independence is non-negotiable for you, and today it's being respected. A situation that could have been constraining instead leaves you room.",
    "Your idealism is a strength, not a naivety. The world you imagine is one worth working toward — hold the vision and take one step in its direction.",
    "An intellectual conversation today goes somewhere unexpectedly deep. You learn something — or teach something — that stays with both of you.",
    "The future arrives in flashes for you before it arrives for others. What's the pattern you're seeing that others haven't named yet?",
    "Community is where your gifts multiply. A group, a network, a movement benefits from your perspective today — show up for it.",
    "Eccentricity is just innovation that hasn't been validated yet. Don't normalize yourself for environments that aren't worth it.",
    "A friendship that's been dormant is ready to be revived. Aquarius connections have a quality of timelessness — reach out without apology for the gap.",
    "Technology, systems, or structures that could work better are catching your attention. Your insight into how to improve them is worth sharing.",
    "The conventional path was never your path. Today's detour is actually the route — trust where your instincts are diverging from the expected direction.",
    "Objectivity is one of your greatest strengths, but today balance it with feeling. The most innovative solutions also consider the human dimension.",
    "Someone misunderstands you today, and it doesn't particularly bother you — which is itself a kind of freedom. Let it pass.",
    "Your vision for something is larger than the current conversation about it. Bring the bigger frame — it helps everyone think more clearly.",
    "A humanitarian impulse asks you to act today — not with grand gestures, but with one specific, practical thing that helps someone real.",
    "Progress is your native desire, and today you can see it happening in a situation you've been watching carefully. Something is genuinely getting better.",
    "Rebellion is useful when it's principled. Today, make sure what you're pushing back against deserves the energy, not just the habitual resistance.",
    "An unusual idea you've been sitting with is more practical than it first appeared. Talk it through with someone who asks good questions.",
    "Your friendship is unusual — independent, stimulating, not always predictable. Today someone values exactly that quality in you.",
    "A collective effort benefits from your ability to see the system rather than just your part of it. Offer the view from altitude.",
    "Logic and intuition are not opposites — your best insights use both. Today the rational and the instinctual arrive at the same place from different directions.",
    "Freedom is a value worth examining: free to do what, exactly? Today, get specific about what your independence is actually in service of.",
    "The status quo is rarely wrong because it's true — it's wrong because it stopped being examined. Your questioning is valuable even when it's inconvenient.",
    "Social energy is high today but keep some in reserve. You recharge alone even when you love people — protect the time that makes that possible.",
    "A sudden insight arrives today — about yourself, a situation, or a person — that reframes something you thought you'd already understood.",
    "Your originality is your contribution. The world has enough people who fit neatly into established categories — your category needs you in it.",
    "Change doesn't frighten you the way it does others. Something shifting today that others find unsettling is simply interesting to you — and your groundedness helps those around you.",
    "The vision you carry of a better world isn't naivety — it's navigation. Keep walking toward it. The distance is shorter than it looked when you started.",
  ],

  Pisces: [
    "Your sensitivity is a finely tuned instrument today, Pisces. What you perceive in the quiet — in a tone of voice, a flicker of feeling, a dream half-remembered — is worth trusting.",
    "Compassion flows from you today without effort. Let it — you're not losing energy when you give it from this place, you're expressing what you're made of.",
    "A creative work that has been forming in the background is ready to come forward. Give it time today — even thirty minutes in a quiet space — and see what surfaces.",
    "Neptune, your ruling planet, dissolves the boundaries between inner and outer today. Pay attention to synchronicities — they're not coincidences.",
    "Your imagination is an asset, not an escape hatch. Used actively, it generates the most beautiful solutions. Used passively, it takes you away from what's real. Today, use it actively.",
    "Something or someone from the past returns to your awareness — not to pull you back, but to complete something that needs completing before you move forward.",
    "Music, water, art, or anything that bypasses the rational mind and speaks directly to your soul is what you need today. Find it.",
    "Your empathy allows you to feel what others are going through with unusual accuracy. Today, let that capacity guide a kindness that lands exactly right.",
    "The line between your feelings and others' feelings is blurry for you — it always has been. Today, gently check: which of these emotions is actually yours?",
    "A spiritual practice or moment of stillness today gives you access to a kind of knowing that analysis doesn't. What arrives in the silence is real.",
    "Your dreams last night had something to say. Even if the details are vague, the feeling they left has information in it — stay with it.",
    "Artistic expression is your medicine. Something that's been building emotionally finds its right channel today in making — writing, drawing, playing, dancing.",
    "The person in your life who is struggling most right now would benefit from your presence more than your words. Simply being there, with attention and without agenda, is profound.",
    "Idealism about a relationship or situation may need gentle reality-checking today — not to destroy the dream, but to help it actually survive contact with the real world.",
    "Your boundaries are worth clarifying today — kindly but specifically. You give so freely that people sometimes take without noticing. This is a gentle correction, not a rejection.",
    "A healing process that's been underway — one you may not have consciously named — is further along than you know. Something tender is becoming stronger.",
    "Solitude restores you in ways that most people don't require or understand. Take the time you need without apologizing for it.",
    "An act of forgiveness — toward someone, or toward yourself — becomes possible today. It doesn't require a conversation; it simply requires an internal choice.",
    "Your intuition is your most reliable navigation system. A logical argument may be persuasive, but what does your body know about this decision?",
    "The beauty in this day is available if you slow down enough to receive it. Pisces energy excels at being moved — let yourself be moved.",
    "Someone's emotional truth is more visible to you today than to anyone around them. Use that perception gently and wisely.",
    "A fantasy or longing that's been sitting quietly deserves honest examination: is this something to move toward, or something to release? Both answers are okay.",
    "Your fluid sense of self is an asset in environments that require adaptability. Today, you fit into a space that would be uncomfortable for most — and you thrive there.",
    "Water heals you — literally. A shower taken slowly, a walk near water, rain listened to from indoors — any of these resets something in you.",
    "A connection made today has a quality of depth and recognition that you've rarely experienced. Don't let the moment pass without acknowledging it.",
    "Sacrifice and martyrdom are different things. Sacrifice is chosen and meaningful; martyrdom is resentment in disguise. Today, know which one you're in.",
    "Your sensitivity to atmosphere is acute today. An environment that feels off will be difficult to work in — if you can change it, do.",
    "The spiritual and the practical are not separate in your life — they inform each other. A practical decision made from spiritual values today has a different quality.",
    "You are more capable of handling the real world than you sometimes believe. Today offers gentle evidence of that.",
    "At the end of this day, rest in the knowledge that simply being open to beauty, to others, and to the invisible dimensions of experience is itself a kind of contribution.",
  ],
};

export default FORTUNES_EN;
