// 360 lecturas diarias de horóscopo — 30 por signo zodiacal occidental.
// Claves en inglés (nombre canónico del signo, compartido entre todos los locales).

const FORTUNES_ES: Record<string, string[]> = {
  Aries: [
    "Un impulso de iniciativa llega hoy — confía en él. El proyecto o conversación que has estado postergando está listo para comenzar. Actúa mientras tu energía está alta.",
    "Tu espíritu competitivo se agudiza esta mañana. Canalízalo hacia algo constructivo y te sorprenderás con lo que logras.",
    "Detente antes de saltar hoy. Tus instintos son confiables, pero un momento de reflexión hará tu próximo movimiento el doble de efectivo.",
    "El liderazgo te llega de manera natural, y hoy alguien observa cómo manejas un desafío. Deja que tus acciones hablen más que tus planes.",
    "La energía física es tu moneda hoy — gástala sabiamente. Una caminata, un entrenamiento, o incluso una conversación enérgica puede reiniciarlo todo.",
    "Un nuevo comienzo está más cerca de lo que parece. La puerta que has estado esperando puede abrirse con un empujón, no con un golpe.",
    "La impaciencia es tu sombra hoy. Nota cuándo te está guiando y pregunta si lo que este momento necesita es velocidad o precisión.",
    "Tu franqueza será más apreciada de lo que esperas hoy. Di lo que piensas — las personas a tu alrededor están listas para escucharlo.",
    "Algo competitivo se agita en ti. Usa ese fuego para motivar en lugar de intimidar, y traerás a otros contigo en lugar de dejarlos atrás.",
    "El descanso es estrategia hoy, no rendición. Incluso el guerrero más audaz sabe cuándo recargar energías antes del próximo avance.",
    "Una oportunidad llega disfrazada de obstáculo. La energía de Aries sobresale encontrando el camino — busca la salida, no el rodeo.",
    "Tu entusiasmo es contagioso hoy. Compártelo libremente y observa cómo las personas a tu alrededor se elevan para igualar tu energía.",
    "Una meta que estableciste hace semanas está al alcance. El empuje final requiere menos de lo que crees — principalmente solo aparecer.",
    "Observa un momento de conflicto hoy. Tu instinto es ganar; el movimiento más sabio puede ser escuchar primero y responder segundo.",
    "El coraje no es la ausencia de duda — es actuar a pesar de ella. Las circunstancias de hoy te piden exactamente eso.",
    "Tu apetito por lo nuevo es un activo. Sigue una curiosidad que te ha estado molestando y ve a dónde lleva el hilo.",
    "Una relación se beneficia de tu honestidad hoy. Sé directo pero cálido — tus palabras tienen más peso del que te das cuenta.",
    "Hoy es un día para comenzar. Escribe la primera línea, haz la primera llamada, da el primer paso. El impulso sigue a la acción.",
    "Tu energía alcanza su pico temprano hoy. Programa tus tareas más exigentes por la mañana y deja la tarde para las más ligeras.",
    "Alguien puede desafiar tu autoridad o ideas hoy. Responde con confianza, no con defensividad — tu historial habla por sí mismo.",
    "La creatividad y la acción se alinean hoy. Si tienes una idea que ha estado esperando, dale forma — incluso un borrador cuenta.",
    "La generosidad te sirve bien hoy. Compartir tu conocimiento o tiempo te cuesta poco y construye algo duradero.",
    "Un problema que has estado atacando de frente puede necesitar un enfoque diferente. Da un paso atrás, mira el panorama completo, luego intenta de nuevo.",
    "Tu planeta regente Marte te da resistencia hoy. Empuja a través de la mitad de una tarea — la línea de meta está más cerca de lo que se siente.",
    "Independiente por naturaleza, a veces olvidas que la colaboración puede amplificar tus resultados. Deja que alguien ayude hoy — no es debilidad.",
    "La espontaneidad es tu amiga hoy. El mejor resultado puede venir del desvío no planificado, no de la ruta cuidadosamente trazada.",
    "Un pequeño acto de valentía — un mensaje enviado, un miedo nombrado, un riesgo tomado — se propagará hacia adelante de maneras que no verás de inmediato.",
    "Reflexiona sobre lo que has comenzado recientemente. ¿Qué proyectos merecen más combustible? Dirige tu fuego donde realmente arderá.",
    "Hoy favorece a los audaces pero recompensa a los preparados. Ten tus hechos listos, tu confianza natural y tu timing paciente.",
    "El día termina mejor de lo que comienza. Supera cualquier fricción matutina y confía en que la tarde tiene algo que vale la espera.",
  ],

  Taurus: [
    "La comodidad es tu derecho hoy, Tauro. Crea el entorno que te ayuda a pensar con claridad — un escritorio ordenado, una buena comida, la música correcta — y tu productividad seguirá naturalmente.",
    "La paciencia está siendo puesta a prueba, pero tu famosa resistencia es exactamente lo que esta situación necesita. El camino lento y constante sigue siendo el correcto.",
    "Un impulso creativo conectado a la belleza o la estética vale la pena seguirlo hoy. Tu ojo para la calidad te hace un curador natural — confía en eso.",
    "Los asuntos financieros merecen una segunda mirada. Un pequeño ajuste ahora — una suscripción cancelada, un presupuesto revisado — se convierte en ahorros reales con el tiempo.",
    "La lealtad te define, y hoy alguien en tu círculo la reconoce. Una palabra silenciosa de aprecio está llegando; recíbela con gracia.",
    "Tus sentidos están agudizados hoy. Una comida compartida, un jardín visitado, una pieza musical permitida tocar completamente — estos no son lujos, son combustible.",
    "La terquedad te sirve cuando tus convicciones son correctas. Hoy, pausa y verifica: ¿lo que estás sosteniendo es sabiduría o hábito?",
    "La seguridad te importa, y eso es saludable. Hoy, da un paso práctico — por pequeño que sea — hacia una meta que te haga sentir más estable.",
    "Venus, tu planeta regente, activa tu encanto hoy. Las interacciones sociales fluyen sin problemas, y un cumplido genuino que des será recordado.",
    "Las mañanas lentas llevan a días constantes. No apresures el inicio — deja que tu ritmo se construya naturalmente y superarás a quienes ardieron brillantemente al amanecer.",
    "Una conversación sobre dinero o recursos con alguien de confianza es oportuna. Las perspectivas compartidas te ayudan a ver opciones que has estado perdiendo.",
    "Tu reputación de confiabilidad está abriendo una puerta ahora mismo. Una oportunidad que llega pronto es en parte gracias a ese historial.",
    "La belleza en las cosas pequeñas — una luz matutina, una nota escrita a mano — tiene un significado especial hoy. Déjate conmover por ella.",
    "Un proyecto que requiere esfuerzo sostenido es exactamente adecuado para tu naturaleza. Comienza el próximo capítulo hoy sin esperar condiciones perfectas.",
    "Puede que sientas resistencia al cambio hoy, y eso es válido nombrarlo. Pero pregunta: ¿cuál es el costo de quedarse quieto comparado con el de moverse?",
    "La comodidad física está ligada a tu estado de ánimo de maneras que a veces pasas por alto. Una siesta, un estiramiento, una comida adecuada — trata bien tu cuerpo y tu perspectiva cambia.",
    "Alguien puede malinterpretar tu calma como indiferencia hoy. Una breve expresión de lo que estás pensando aclarará un malentendido antes de que crezca.",
    "La posesividad puede disfrazarse de cuidado. Hoy, nota si te estás aferrando a algo — o alguien — por amor o por miedo.",
    "Una meta a largo plazo recibe un impulso hoy. El trabajo que has estado haciendo silenciosamente durante semanas está comenzando a acumularse en algo visible.",
    "Tu gusto y criterio son guías confiables. Cuando todos los demás están inciertos, tus instintos arraigados a menudo apuntan a la respuesta correcta.",
    "La naturaleza te restaura. Si puedes pasar aunque sea quince minutos afuera hoy, hazlo. Tu cuerpo sabe lo que tu mente a veces olvida.",
    "Una amistad o conexión antigua resurge. La energía de Tauro mantiene los vínculos vivos — comunícate y descubre que la calidez nunca realmente se fue.",
    "La practicidad es tu superpoder. Antes de dejarte llevar por una idea emocionante, haz las preguntas básicas: ¿Qué cuesta esto realmente? ¿Qué requiere realmente?",
    "Hoy es adecuado para tareas que requieren concentración y oficio. Pon algo que ames escuchar y haz el trabajo que requiere tu plena atención.",
    "La generosidad fluye fácilmente de ti hoy. Un regalo de tiempo, comida o atención genuina significa más viniendo de ti que de casi cualquier otra persona.",
    "Confía en tu ritmo. Trabajas en ciclos más largos que la mayoría — no juzgues el progreso de hoy por el ritmo de otra persona.",
    "Un pequeño pero significativo placer te espera en el día — nótalo cuando llegue y permítete disfrutarlo completamente en lugar de pasarlo de largo.",
    "Tus valores son tu brújula. Cuando una decisión se siente complicada, regresa a la pregunta: ¿qué creo que realmente importa aquí?",
    "Venus trae calidez a tus relaciones más cercanas hoy. Un momento de atención plena ofrecido a alguien que amas aterriza hermosamente.",
    "La tortuga gana no por velocidad sino por aparecer sin detenerse. Hoy es solo un paso más en un viaje que ya está más lejos de lo que a veces reconoces.",
  ],

  Gemini: [
    "Tu mente corre rápido hoy, Géminis — dale un problema digno que resolver y observa lo que emerge. El aburrimiento es tu único enemigo real.",
    "Una conversación que no planeaste será lo más interesante que suceda hoy. Di que sí al intercambio inesperado.",
    "Dos ideas que has estado sosteniendo por separado de repente se conectan. Escríbelo de inmediato — la síntesis es la perspectiva.",
    "La comunicación es tu fortaleza y hoy está especialmente aguda. Un mensaje, correo electrónico o presentación llega exactamente como se pretendía.",
    "Mercurio, tu planeta regente, agudiza tu ingenio hoy. Úsalo para deleitar en lugar de desviar — las personas que entienden tu humor valen la pena encontrar.",
    "Tu adaptabilidad está siendo llamada. Una situación que cambia inesperadamente es en realidad mejor adecuada para tus habilidades que el plan original.",
    "La curiosidad te lleva a algún lugar útil hoy. Sigue el hilo de una pregunta que ha estado en el fondo de tu mente — lleva a algún lugar que vale la pena.",
    "Una mañana inquieta da paso a una tarde productiva. Deja que las ideas circulen en las primeras horas; la claridad llegará al mediodía.",
    "El multitasking es tu modo natural, pero hoy una tarea merece tu enfoque singular. El resultado te sorprenderá.",
    "Algo que lees, escuchas o ves genera una idea que vale la pena conservar. Ten algo cerca para capturarlo — tus mejores pensamientos se mueven rápido.",
    "Una relación se beneficia de una conversación real hoy — no la verificación rápida, sino la real. Haz tiempo para la profundidad.",
    "Tu versatilidad abre una puerta hoy que permanecería cerrada para personas menos adaptables. Pasa por ella sin pensar demasiado.",
    "La indecisión te visita hoy, como a veces sucede. Elige la opción que te emociona más — cualquier camino es viable; el impulso hacia adelante es lo que importa.",
    "Enseña algo hoy, aunque sea de manera informal. Explicar lo que sabes lo clarifica para ti tanto como ayuda al oyente.",
    "La energía social es alta y las conexiones son fáciles. Una introducción hecha hoy podría volverse importante de maneras que ninguno de los dos espera.",
    "Tu tendencia a ver múltiples lados es un don, pero comprométete cuando llegue el momento. Una decisión tomada a medias es más difícil de vivir que una tomada.",
    "La ligereza está subestimada. No dejes que nadie — incluido tú mismo — te haga sentir que la alegría es menos seria que la seriedad.",
    "Un viaje corto, mandado, o cambio de ambiente restablece tu pensamiento completamente. Incluso veinte minutos en algún lugar diferente desbloquea una perspectiva fresca.",
    "Estás procesando más de lo que estás mostrando hoy. Date una hora tranquila antes de dormir para dejar que los insumos del día se asienten.",
    "Escribir clarifica lo que hablar solo hace circular. Pasa diez minutos poniendo tus pensamientos actuales en papel — sabrás más sobre ti mismo después.",
    "Tu encanto está trabajando a tu favor hoy. La gente quiere ayudarte — déjala.",
    "La energía dispersa puede ser redirigida en lugar de suprimida. Escribe una lista de tres prioridades y comienza con la más interesante.",
    "Una idea o proyecto olvidado merece una segunda mirada. Lo que parecía complicado entonces puede ser sorprendentemente abordable ahora.",
    "Tu capacidad para conectar a diferentes personas es valiosa. Una introducción o recomendación que hagas hoy sirve a todos los involucrados.",
    "Los nervios y la emoción se sienten similares en el cuerpo. Lo que estás sintiendo antes de algo nuevo podría ser igualmente lo último.",
    "El lenguaje importa hoy — las palabras que eliges llevan peso extra. Sé preciso con el significado y generoso con el tono.",
    "El aburrimiento es tu señal de que se necesita crecimiento. Si hoy se siente plano, pregunta: ¿qué me desafiaría realmente ahora mismo?",
    "Un impulso doble — quedarse e irse, hablar y escuchar — se resuelve cuando eliges uno y te comprometes. Confía en el primer instinto.",
    "La información llega de una fuente inesperada. Algo escuchado, vislumbrado, o compartido casualmente resulta ser exactamente lo que necesitabas saber.",
    "Tu mente es un jardín, no una máquina. Riégala con curiosidad, dale variedad, y no te sorprendas cuando las cosas hermosas crezcan en los márgenes.",
  ],

  Cancer: [
    "Tu intuición es más clara cuando estás quieto, Cáncer. Toma cinco minutos esta mañana antes de que comience el ruido — lo que sientas en esa quietud vale la pena confiar.",
    "Alguien en tu vida necesita exactamente lo que se te da naturalmente: sentirse verdaderamente escuchado. Ofrece eso hoy y el regalo te regresa de maneras que no esperas.",
    "El hogar es tu santuario, y algo en tu espacio está pidiendo atención. Un pequeño cambio — reorganizar, limpiar, o añadir algo — mejora toda tu semana.",
    "Un recuerdo surge hoy que lleva tanto calidez como dolor. Déjate sentirlo sin juzgarlo — es parte de cómo te mantienes conectado a lo que importa.",
    "Tu capacidad de cuidar es notable, pero hoy verifica que te estás incluyendo en ese círculo de cuidado. No puedes verter de un recipiente vacío.",
    "La Luna, tu planeta regente, amplifica las emociones hoy. Esto es una característica, no un error — tus sentimientos son datos. ¿Qué te están diciendo?",
    "Un proyecto creativo conectado al hogar, la familia, o la historia personal está esperando. Incluso veinte minutos de atención dados a él mueven algo hacia adelante.",
    "La protección surge en ti hoy, quizás hacia alguien más joven, más nuevo, o más vulnerable. Confía en ese instinto — tu refugio es real.",
    "Una conversación que se siente arriesgada comenzar en realidad está lista para tenerse. Tu sensibilidad te ayuda a decir cosas difíciles de maneras que sanan en lugar de dañar.",
    "La nostalgia te visita hoy, no para mantenerte atascado sino para recordarte lo que has construido. Has llegado más lejos de lo que a veces recuerdas.",
    "La seguridad financiera y la seguridad emocional están vinculadas para ti — atiende una y la otra a menudo mejora. Un pequeño paso práctico hoy alivia ambas.",
    "Tu empatía es una fortaleza, pero absorber las emociones de otros sin un filtro te agota. Nota de quién estás cargando sentimientos y suavemente déjalos ir.",
    "La creatividad fluye del sentimiento hoy. No esperes inspiración — comienza desde donde tus emociones realmente están, y el trabajo será honesto.",
    "Cocinar, jardinear, o cualquier acto de creación nurturante te restaura. Prográmalo deliberadamente hoy en lugar de esperar que encaje.",
    "Una relación con un familiar está lista para una reparación suave. Sabes lo que decir — el momento es mejor de lo que piensas.",
    "Tu lealtad corre profunda y larga. Hoy puedes ver evidencia de que alguien que has apoyado ha crecido de maneras que tu inversión ayudó a hacer posible.",
    "La vulnerabilidad no es tu enemigo — la fortaleza actuada sí lo es. Deja que alguien entre un poco más hoy y descubre lo que la confianza realmente se siente.",
    "Algo que has estado protegiendo ya no necesita ser protegido. La concha que te mantuvo seguro se ha convertido en lo que te mantiene pequeño.",
    "Los sueños llevan información para ti de maneras que vale la pena tomar en serio. Lo que apareció anoche puede ser un mensaje que vale la pena sentarse con él.",
    "Tu cuidado por los demás es interminable, pero el duelo, la frustración, o la preocupación a veces se visten de ocupación. Desacelera lo suficiente para notar lo que realmente sientes.",
    "Un acto de creatividad doméstica — cocinar algo nuevo, hacer algo con tus manos — satisface una necesidad de expresión que nada más hace del todo.",
    "Un amigo se comunica hoy. Acepta la invitación, incluso si tu primer instinto es decir que estás demasiado ocupado. La conexión te repone.",
    "Los límites establecidos desde el amor, no el miedo, son sostenibles. Hoy es un buen día para articular — clara pero amablemente — lo que necesitas de alguien cercano.",
    "Los niños, los animales, o cualquiera que necesite una mano suave son atraídos por tu energía hoy. Permítete estar completamente presente para ellos.",
    "La seguridad no es algo que encuentras — es algo que construyes. Un pequeño paso tomado hoy hacia una base más estable es exactamente el ritmo correcto.",
    "Tu mundo interior es rico y a veces abrumador. Escribir, dibujar, o simplemente sentarte en silencio da a la emoción un lugar donde aterrizar.",
    "Un miedo de larga data sobre el cambio puede relajarse ligeramente hoy cuando ves que algo por lo que estabas preocupado está yendo mejor de lo esperado.",
    "Las personas que has elegido como familia — de sangre o no — merecen saber que les importas. Dilo en voz alta hoy. No quedará sin decir dos veces.",
    "La intuición y la lógica tienen un papel hoy. Confía en la lectura del instinto pero verifica los detalles antes de comprometerte. Descubrirás que están de acuerdo más a menudo de lo que no.",
    "El descanso y la restauración son actos productivos para ti — no indulgencias. Lo que tu cuerpo y emociones necesitan esta noche, dáselos sin culpa.",
  ],

  Leo: [
    "El foco te encuentra hoy, Leo — déjalo. Tu presencia genuinamente eleva la energía en una habitación, y este no es el día para encogerte ante eso.",
    "La creatividad es tu oxígeno, y algo nuevo quiere ser hecho. Da una hora hoy a cualquier forma de creación que más te haga sentir vivo.",
    "Tu generosidad es uno de tus mayores dones. Una oportunidad de dar — tu tiempo, tu plataforma, tu aliento — llega hoy. Tómala.",
    "El orgullo puede proteger o aislar dependiendo de cómo lo uses. Hoy, pregunta: ¿esta confianza me sirve, o me mantiene alejado de algo que realmente necesito?",
    "El Sol, tu planeta regente, está detrás de todo lo que inicias hoy. Comienza algo. Anuncia algo. Comprométete a algo. La energía está allí.",
    "La lealtad corre profunda en ti, y un amigo necesita eso hoy — no consejos, solo tu presencia firme. Estate allí sin necesitar arreglar nada.",
    "El reconocimiento por algo que hiciste hace semanas o meses llega hoy. Acéptalo completamente — lo ganaste y desviarlo no sirve a nadie.",
    "El drama en el entorno se aborda mejor con autoridad tranquila que igualando la intensidad. Tu calma es lo más poderoso en la habitación.",
    "Tu carácter juguetón es uno de tus rasgos más subestimados. Hoy es un día para dejarlo salir — la risa, la creatividad y la diversión no son frívolas, son tu naturaleza.",
    "Un proyecto creativo a medio camino necesita tu confianza para terminarlo. La duda que sientes es normal; el trabajo es mejor de lo que piensas.",
    "Alguien más joven o con menos experiencia necesita tu mentoría. Tu disposición a compartir lo que sabes es una forma de liderazgo que importa más de lo que te das cuenta.",
    "Tu calidez llega a alguien que ha estado pasando por un período frío. Un acto simple y generoso hoy significa más de lo que sabes.",
    "La ambición se agita hoy. Una meta que habías dejado de lado vuelve a tu mente — esta vez con un sentido más claro de cómo abordarla.",
    "La vanidad y el autorespeto son cosas diferentes. Una se alimenta de la aprobación de otros; la otra no la necesita. Hoy se te llama a conocer la diferencia.",
    "La colaboración brilla cuando estás en ella. Comparte el escenario hoy y descubrirás que el reconocimiento es en realidad mayor para todos los involucrados.",
    "Una actuación — literal o metafórica — va bien hoy. Has preparado más de lo que piensas; confía en tus instintos en el momento.",
    "Los niños, los animales, o los espíritus juguetones te buscan hoy. Acepta la invitación de ser menos serio de lo usual. La alegría es una prioridad legítima.",
    "Tu instinto de proteger a las personas que amas es fuerte hoy. Canalízalo en acción — el apoyo práctico habla más alto que la preocupación.",
    "El aburrimiento señala que estás listo para un desafío más grande. Si hoy se siente demasiado pequeño, es porque lo eres.",
    "Un gesto romántico — espontáneo, sincero, no planificado — crea un recuerdo hoy que dura más que cualquier cosa programada.",
    "El liderazgo no siempre es ruidoso. Hoy, lidera escuchando primero y hablando segundo. La sala seguirá a alguien que la entiende.",
    "Tus instintos estéticos están agudos hoy. Confía en ellos en decisiones creativas, elecciones de interiores, o cualquier cosa donde el gusto sea el factor decisivo.",
    "Algo que estás creando merece ser visto. Compártelo — aunque sea de una pequeña manera. El arte mantenido en privado no sirve a nadie.",
    "Los celos, si visitan, son una brújula que apunta hacia algo que quieres. No los suprimas; tradúcelos en dirección.",
    "Un cumplido que des hoy aterriza con una profundidad inusual. Tienes una manera de nombrar lo que es verdad en las personas — usa ese don.",
    "El descanso no es derrota. Incluso los leones se acuestan en la sombra. Hoy, ¿qué tipo de descanso restaura tu plena fuerza?",
    "Tu pasión por algo es contagiosa de la mejor manera posible. La persona con quien la compartas hoy recibirá la llama.",
    "Un viejo sueño resurge — más pequeño ahora que has crecido más allá del miedo de él. Puede ser el momento adecuado para finalmente darle vida.",
    "Tu mejor yo aparece cuando te sientes visto, así que hoy pasa tiempo con personas que realmente te ven. Cualquier otra cosa está desperdiciando tu energía.",
    "Hoy termina con algo de lo que estar genuinamente orgulloso. Puede ser pequeño según los estándares del mundo — no lo es según los tuyos, y los tuyos son los que importan.",
  ],

  Virgo: [
    "Tu ojo para los detalles capta algo hoy que los demás pasaron por alto por completo, Virgo. Confía en esa observación — cambia el resultado significativamente.",
    "El servicio es significativo para ti, y una oportunidad genuina de ayudar llega hoy. Dala plenamente, sin llevar la cuenta — este es el tipo de ayuda que te sustenta.",
    "El sistema que has querido mejorar está listo para ser mejorado. Un pequeño ajuste en cómo trabajas u organizas ahorra tiempo significativo durante semanas.",
    "El perfeccionismo es una herramienta útil y un amo agotador. Hoy, pregunta: ¿cuál es el estándar que esto realmente requiere, y a qué estoy aplicando estándares que no necesita?",
    "Mercurio, tu planeta regente, agudiza tu análisis hoy. Una situación compleja que ha sido difícil de leer se vuelve legible — ves lo que realmente está pasando.",
    "Los hábitos de salud que se han relajado merecen un restablecimiento suave. Una pequeña corrección hoy — no una revisión drástica — inicia el impulso en la dirección correcta.",
    "Tu naturaleza práctica resuelve lo que otros filosofan. Alguien a tu alrededor tiene un problema real — ya puedes ver la solución.",
    "La atención al oficio es lo que separa lo bueno de lo excelente. Hoy tienes el enfoque para llevar algo de uno al otro.",
    "La preocupación es una forma de pensar que no se completa a sí misma. Cuando el bucle comience, escribe de qué estás realmente preocupado y qué, específicamente, puedes hacer al respecto.",
    "Tu ayuda es profundamente genuina, por eso también a veces agota. Hoy, ofrece un acto generoso y luego protege el resto de tu energía.",
    "Un análisis que has estado haciendo silenciosamente sobre una situación es correcto. Confía en tus conclusiones y actúa sobre ellas — los datos que has reunido son sólidos.",
    "La humildad y la autodepreciación son cosas diferentes. Puedes ser modesto sobre tu conocimiento mientras aún confías en tu experiencia. Hoy, confía en ella.",
    "Un proyecto creativo se beneficia de tus instintos de edición. A veces el acto más creativo es saber qué eliminar.",
    "Tu cuerpo está comunicando algo hoy — una tensión, un cansancio, una señal que has estado ignorando. Escúchala antes de que tenga que volverse más ruidosa.",
    "La crítica ofrecida con cuidado es un regalo. Si alguien ha ganado tu retroalimentación honesta hoy, dala — pero lidera con lo que está funcionando.",
    "La organización es terapéutica para ti. Si el día se siente inmanejable, pasa diez minutos creando estructura — una lista, un plan, una prioridad clara — y observa cómo tu ansiedad disminuye.",
    "Algo que das por sentado sobre tu propia competencia es genuinamente excepcional. Deja que alguien te lo recuerde hoy sin argumentar.",
    "El discernimiento es una de tus cualidades más fuertes. Sabes la diferencia entre lo que vale tu tiempo y lo que no — aplica ese estándar hoy.",
    "Una relación se beneficia de tu claridad. Puedes nombrar lo que funciona y lo que no sin crueldad — esa es una habilidad rara. Úsala.",
    "La rutina no es el enemigo de la creatividad — para ti, es el recipiente que hace posible la creatividad. Protege tus mejores rutinas hoy.",
    "Algo pequeño hecho con extraordinario cuidado hoy — un mensaje, una comida, un detalle en un proyecto — demuestra una clase de excelencia que se acumula.",
    "Tu crítico interno es útil hasta cierto punto. Nota cuándo cruza de ayudarte a mejorar a simplemente agotarte — y dile firmemente que descanse.",
    "Un problema práctico que parecía atascado se vuelve solucionable hoy. La pieza faltante era una conversación que aún no has tenido — tenla.",
    "Tu capacidad para el trabajo sostenido es notable. Un proyecto que requiere enfoque profundo es exactamente adecuado para la energía de hoy — reserva el tiempo y entra.",
    "Ves lo que otros pasan por alto: el defecto en el plan, el vacío en el argumento, la posibilidad en el problema. Hoy, comparte esa perspectiva.",
    "La pulcritud y la claridad en tu entorno se traducen directamente en pulcritud y claridad en tu pensamiento. Si uno está desajustado, atiéndelo.",
    "Alguien necesita el tipo de ayuda metódica y reflexiva que tú das mejor que casi cualquiera. Di que sí.",
    "El análisis sin acción es una forma de procrastinación. Has reunido suficiente información — el siguiente paso es comenzar.",
    "Un hábito de bienestar que has querido iniciar está listo para comenzar. No la próxima semana, no cuando las condiciones sean perfectas — hoy, un pequeño paso.",
    "Al final de hoy, permítete reconocer lo que hiciste bien. El estándar que te impones es alto — cumplirlo, aunque sea parcialmente, merece reconocimiento.",
  ],

  Libra: [
    "El equilibrio es tanto tu don como tu práctica, Libra. Nota dónde se inclina tu vida hoy — no para juzgarlo, sino para ajustarlo suavemente.",
    "Tus instintos diplomáticos son exactamente lo que una situación necesita ahora mismo. Entra donde otros están evitando — sabes cómo hacer que ambos lados se sientan escuchados.",
    "La belleza te nutre de maneras que van más allá de la estética. El tiempo pasado con algo — o alguien — genuinamente hermoso restaura tu equilibrio.",
    "Una decisión que has estado evitando está lista para ser tomada. Reúne el último bit de información que necesitas, luego comprométete. Una decisión tomada, aunque imperfectamente, es más saludable que el pesaje perpetuo.",
    "Venus, tu planeta regente, activa tu encanto y gracia hoy. Las situaciones sociales fluyen fácilmente — estás en tu momento más magnético de una manera tranquila y elegante.",
    "La justicia te importa profundamente. Hoy puedes ser testigo de algo que no está del todo bien y tendrás que decidir: ¿es este el momento de decir algo?",
    "Una colaboración creativa funciona hermosamente hoy. Tu sentido de armonía te hace un socio ideal en cualquier esfuerzo creativo conjunto.",
    "Las relaciones prosperan con atención, y hoy una de las tuyas merece la tuya. Una hora enfocada y sin distracciones con alguien que te importa restaura algo en ambos.",
    "Tu tendencia a ver todos los lados puede ser un don — úsalo para entender, no para evitar elegir. Al final del día, elige.",
    "La paz a cualquier precio no es paz real. Si has estado guardando silencio sobre algo importante para evitar el conflicto, hoy ofrece una apertura suave para hablar.",
    "Las elecciones estéticas hechas hoy — en tu espacio, tu apariencia, tu trabajo creativo — te satisfarán de maneras que duran más de lo que esperas.",
    "Una situación injusta que has estado monitoreando está cambiando. La paciencia y la integridad juntas son más poderosas que la reacción.",
    "La armonía en tu entorno hogareño influye en todo lo demás. Un pequeño esfuerzo para hacer tu espacio más hermoso u ordenado paga dividendos sorprendentes hoy.",
    "El compromiso es un arte, y lo practicas mejor que la mayoría. Hoy, sin embargo, verifica que el compromiso aún incluye tus necesidades reales.",
    "Alguien necesita tu evaluación honesta hoy, no tu evaluación medida. Puedes ser amable y directo al mismo tiempo — Libra hace esto mejor que cualquier otro signo.",
    "La gracia social es effortless hoy. Puedes hacer que las personas se sientan cómodas sin siquiera intentarlo — un don que hace más diferencia de lo que sabes.",
    "Una asociación — personal o profesional — está lista para pasar a un nuevo nivel. La conversación que la inicia es más simple de lo que has estado anticipando.",
    "Tu sentido de la equidad es una brújula. Cuando algo se siente mal hoy — en un sistema, una relación, una decisión — ese instinto vale la pena escuchar.",
    "La indecisión a veces oculta una verdad más profunda: ya sabes lo que quieres, pero tienes miedo de lo que significa elegirlo. Hoy, sé valiente sobre saber.",
    "El arte, la música, la poesía, o cualquier forma de belleza que te mueve es medicina hoy. Prográmalo deliberadamente, no como recompensa para cuando todo lo demás esté hecho.",
    "Un desacuerdo se maneja mejor a través de la curiosidad que la persuasión hoy. Haz preguntas a las que genuinamente no conoces las respuestas.",
    "Tu inclinación natural hacia que todos se lleven bien es admirable pero no siempre realista. Hoy, deja que alguien más navegue la tensión mientras simplemente observas.",
    "Una decisión tomada desde los valores — no desde lo que crees que otros quieren — tiene una calidad diferente. ¿Qué quieres realmente aquí?",
    "La gracia bajo presión es una especialidad de Libra. Una situación hoy que se siente cargada se beneficiará de exactamente la energía tranquila y medida que traes.",
    "Las conexiones hechas hoy llevan peso extra. Una introducción, una conversación, un momento de encuentro genuino — estas importan más de lo que parecen.",
    "Tu apreciación por la calidad sobre la cantidad aplica al tiempo tanto como a cualquier otra cosa. Un día más corto y más significativo supera a uno más largo y disperso.",
    "Un desequilibrio que has estado tolerando — en una relación, una carga de trabajo, una situación — está listo para ser nombrado y abordado. La conversación está atrasada.",
    "La creatividad fluye cuando tu mente está tranquila. Da un paseo, escucha algo hermoso, o pasa tiempo en un espacio que te calma antes de comenzar.",
    "Llevas las perspectivas de las personas con cuidado. Hoy, alguien te confía algo vulnerable — sostenlo suavemente, responde reflexivamente.",
    "Al final de hoy, algo se sentirá más tranquilo de lo que estaba al inicio. No porque el mundo cambió — porque encontraste tu punto de apoyo dentro de él.",
  ],

  Scorpio: [
    "Tu percepción corta hasta lo real hoy, Escorpio. Confía en lo que ves debajo de la superficie — la corriente subterránea que has detectado vale la pena seguir.",
    "Una transformación está en marcha, aunque aún no sea visible desde afuera. Confía en el proceso que ocurre en las profundidades — la metamorfosis es real.",
    "La intensidad es tu modo, y hoy es un activo. Cualquier cosa en la que te enfocas recibe toda la fuerza de tu atención — elige sabiamente.",
    "Un secreto que has guardado — incluso de ti mismo — quiere ser reconocido hoy. La verdad que ya conoces está lista para ser vivida.",
    "Plutón, tu planeta regente, profundiza todo lo que tocas hoy. Una conversación que comienza de una manera termina en un lugar que ninguno esperaba — y mejor por ello.",
    "Tu capacidad de lealtad llega a grandes profundidades. Alguien en tu círculo ha ganado más confianza de la que le has dado — hoy es el día de ofrecerla.",
    "La pasión bien dirigida crea. La pasión dirigida sin objetivo quema. Hoy, sé intencional sobre lo que te estás vertiendo.",
    "Algo que termina hoy está haciendo espacio para algo que no podría haber llegado mientras lo viejo todavía estaba allí. Déjalo ir.",
    "Tus instintos sobre alguien son precisos. No siempre necesitas actuar sobre ellos de inmediato — sentarse con lo que percibes te da una ventaja.",
    "Un deseo que ha estado acechando en los bordes de tu conciencia merece un reconocimiento honesto. ¿Qué quieres realmente — no lo que se supone que debes querer?",
    "La dinámica del poder te interesa, pero observa la diferencia entre entenderla y ser controlado por ella. Eres más poderoso cuando eres libre.",
    "Una sanación — de una relación, una herida, una tensión sostenida durante mucho tiempo — se vuelve posible hoy. No tienes que apresurarlo, pero puedes abrir la puerta.",
    "La investigación, la investigación o la lectura profunda alimenta algo en ti que la estimulación superficial no puede. Dale a tu mente algo en lo que valga la pena profundizar.",
    "Sientes lo que está cambiando antes de que otros lo nombren. Usa esa percepción para prepararte en lugar de temer.",
    "La vulnerabilidad no es tu postura natural, pero hoy es lo que crea la conexión que realmente quieres. Deja que alguien vea más de ti de lo que usualmente permites.",
    "Un rencor que ha estado funcionando silenciosamente en el fondo te cuesta energía que podrías usar para otra cosa. Liberarlo no es perdonarlos — es libertad para ti.",
    "Tu presencia magnética atrae a personas hoy sin esfuerzo. Sé consciente de quién estás invitando a tu órbita.",
    "Algo que has estado investigando — una situación, una persona, una idea — se vuelve más claro hoy. La imagen se ensambla si sigues mirando.",
    "La transformación rara vez es cómoda, pero siempre es tu terreno más natural. Sabes cómo sobrevivir la reinvención — lo has hecho antes.",
    "Un asunto financiero merece atención cercana hoy. Tus instintos sobre dónde algo no cuadra valen la pena seguir.",
    "El silencio que guardas puede ser sabiduría o distancia. Hoy, nota cuál es — y si es distancia, ciérrala.",
    "Tu profundidad de sentimiento es uno de tus mayores dones, incluso cuando es pesado. Lo que sientes, lo sientes completamente — no te pidas sentir menos.",
    "La confianza y el control están en tensión hoy. No puedes tener ambos completamente — ¿cuál importa más en esta situación?",
    "Algo oscuro que has estado mirando honestamente está perdiendo algo de su poder sobre ti. Entenderlo fue el primer paso. Este es el segundo.",
    "La sexualidad, la creatividad y el poder son todas expresiones de la misma energía fundamental en ti. Hoy, canalízala conscientemente.",
    "Un sueño o imagen recurrente ha estado tratando de decirte algo. El inconsciente de Escorpio rara vez es aleatorio — ¿qué símbolo ha estado apareciendo?",
    "Tu capacidad de regeneración es extraordinaria. Lo que has pasado habría quebrado a alguien con menos profundidad. Reconstruiste — y todavía estás construyendo.",
    "La obsesión y la pasión se sienten similares por dentro pero producen resultados diferentes. Verifica: ¿esto te está consumiendo o alimentando?",
    "Lo que proteges más ferozmente a veces necesita ser liberado precisamente porque lo amas tanto. Hoy, considera qué está protegiendo realmente el aferrarse.",
    "Al final de este día, algo es diferente en ti — aunque nadie más pueda verlo. Los cambios de Escorpio ocurren de adentro hacia afuera, y son permanentes.",
  ],

  Sagittarius: [
    "El horizonte siempre te llama, Sagitario, y hoy tiene algo específico que decir. Sigue la curiosidad que te apunta hacia afuera — literalmente o a través de un libro, una conversación, una nueva perspectiva.",
    "El optimismo es tu lengua materna, y hoy es contagioso. Compártelo libremente — tu disposición a creer que las cosas pueden ser mejores inspira a las personas más de lo que admiten.",
    "Una aventura está lista para comenzar, aunque empiece como una pequeña desviación de la rutina. Di que sí a lo que rompe el patrón.",
    "Tu mente filosófica está luchando con una gran pregunta hoy. Déjala. La búsqueda es tan valiosa como la respuesta — quizás más.",
    "Júpiter, tu planeta regente, expande todo lo que tocas hoy. Comienza algo, y observa cómo crece más grande y más rápido de lo esperado.",
    "La libertad es tu necesidad central, y hoy puedes sentirla limitada. Nombra lo que te está limitando — y luego decide si el límite es real o percibido.",
    "Un maestro llega hoy en una forma inesperada — el comentario casual de un extraño, un libro que se abre en cierta página, un desafío que contiene una lección.",
    "Tu honestidad es rara y a veces sorprendente. Hoy, encuentra el momento donde es genuinamente útil — y comparte lo que ves sin editarte a ti mismo hasta la vaguedad.",
    "Un plan que requiere flexibilidad juega a tus fortalezas. Las estructuras rígidas te frustran; los viajes de final abierto son donde prosperas.",
    "Viajar — incluso del tipo de sillón — alimenta algo en ti que nada más hace. Explora algún lugar hoy, aunque sea desde tu escritorio.",
    "Tu entusiasmo por las ideas es un regalo para las personas a tu alrededor. Lo que más te emociona ahora mismo vale la pena hablar de ello.",
    "Un riesgo que ha estado en tu estante mental está listo para ser tomado. No imprudentemente — pero con el conocimiento de que la seguridad y el crecimiento rara vez coexisten.",
    "Alguien necesita escuchar que las cosas van a estar bien — y necesita escucharlo de ti, porque lo dices como si lo dijeras en serio. Porque sí.",
    "Tu amor por el aprendizaje no requiere una estructura formal. La lección de hoy puede venir de un video, un paseo, una conversación en la cena — mantente abierto.",
    "La pregunta es más valiosa que la respuesta hoy. Pregunta lo que has tenido miedo de preguntar — de ti mismo o de alguien más — y ve qué regresa.",
    "Tu perspectiva global te ayuda a ver una situación local con una claridad inusual. Aleja el zoom en un problema que se ha sentido demasiado cercano y observa cómo se vuelve solucionable.",
    "El compromiso y la libertad se sienten como opuestos para ti, pero las aventuras más profundas requieren ambos. ¿A qué estás dispuesto a comprometerte para ir más lejos?",
    "Una creencia que has sostenido durante mucho tiempo puede estar lista para evolucionar. Un Sagitario que deja de cuestionar es un Sagitario que ha dejado de crecer.",
    "Tu energía física necesita una salida hoy. El movimiento — un paseo, una carrera, un desvío espontáneo — no es opcional, es mantenimiento.",
    "La generosidad te viene naturalmente, y hoy fluye especialmente libremente. Da lo que tienes — sabiduría, risa, o recursos — y no lo cuentes.",
    "Una convergencia afortunada se está construyendo hoy. Tres cosas que parecían no relacionadas están a punto de conectarse de una manera que abre una puerta.",
    "Eres alérgico a las apariencias, y hoy la autenticidad de alguien es refrescante de una manera que no esperabas. Pasa más tiempo con personas que son reales.",
    "Algo que siempre has querido experimentar está más cerca de ser posible de lo que has estado asumiendo. ¿Qué primer paso podrías dar hoy?",
    "Enseñar y aprender son el mismo acto visto desde diferentes direcciones. Lo que compartes hoy te enseña algo sobre lo que realmente sabes.",
    "Tu planeta regente Júpiter gobierna la suerte, y hoy estás en su corriente. Estira un poco más de lo que crees que puedes — la distancia es más corta de lo que parece.",
    "La inquietud es una señal, no un defecto. ¿Hacia dónde apunta la tuya? Está tratando de llevarte a algún lugar.",
    "Una conversación espiritual o filosófica te encuentra hoy — y algo dicho cambia tu perspectiva de una manera pequeña pero duradera.",
    "¿Cuál es la cosa más grande que podrías posiblemente hacer con lo que tienes ahora mismo? Hoy, da un paso hacia esa respuesta.",
    "La risa está subestimada como medicina. El día que incluye risa genuina, incontrolable, es un día que ha ido bien.",
    "Viniste aquí a buscar, a encontrar, y a seguir buscando. Hoy simplemente confirma que el viaje es exactamente lo que debía ser.",
  ],

  Capricorn: [
    "Tu ambición no es arrogancia, Capricornio — es una forma de fe en lo que es posible. Hoy, actúa desde esa fe.",
    "Saturno, tu planeta regente, recompensa al paciente y al persistente. El progreso que has hecho — incluso las partes invisibles desde afuera — es real y se acumula.",
    "Una meta que alguna vez pareció imposiblemente distante ahora es simplemente una cuestión de ejecución continua. Sigue exactamente como has estado.",
    "La responsabilidad te es natural, pero incluso la persona más capaz tiene límites. Delega algo hoy que no te requiere específicamente a ti.",
    "Un problema práctico cede a una solución práctica hoy — no complicada. La respuesta más simple suele ser la correcta.",
    "Tu reputación de confiabilidad está abriendo una puerta ahora mismo. Una oportunidad que llega esta semana es en parte porque las personas saben que pueden contar contigo.",
    "La disciplina es tu herramienta más poderosa y también tu rasgo más reconocible. Hoy está trabajando invisiblemente a tu favor — de maneras que pronto serán visibles.",
    "El estatus te importa, y no hay vergüenza en eso. La pregunta hoy es: ¿lo que estás persiguiendo está genuinamente alineado con lo que valoras, o con lo que crees que deberías querer?",
    "Una decisión financiera se puede tomar con más confianza de la que estás sintiendo actualmente. Tienes la información — confía en tu análisis.",
    "Tu sentido del humor es más seco y agudo de lo que la gente espera. Hoy, déjalo salir. Eres más gracioso de lo que tu seriedad deja ver a las personas.",
    "El liderazgo con el ejemplo es tu punto más fuerte. Alguien está observando cómo manejas una situación difícil y aprendiendo algo que llevarán adelante.",
    "El tiempo es tu relación, no tu enemigo. Una inversión a largo plazo — de esfuerzo, enfoque, o recursos — tiene más sentido hoy que cualquier atajo.",
    "Una conversación sobre tu futuro — con un mentor, un colega de confianza, o simplemente contigo mismo — clarifica lo que estás construyendo y por qué.",
    "El perfeccionismo en Capricornio a menudo señala que te importa, no que tienes miedo. Hoy, verifica cuál está en control.",
    "Algo construido lentamente está comenzando a mostrar resultados. La acumulación de esfuerzo consistente tiene un efecto compuesto — estás en esa fase ahora.",
    "La ética de trabajo no es sustituto de la alegría. Hoy, encuentra al menos un momento donde lo que estás haciendo alinea lo que tienes que hacer con lo que quieres hacer.",
    "Tu energía de anciano o mentor está siendo solicitada hoy. Alguien más nuevo en su viaje se beneficiará exactamente de lo que ya has aprendido.",
    "La montaña que estás escalando es tuya. No compares tu altitud con la de nadie más — están en una montaña completamente diferente.",
    "Un revés es un punto de datos, no un veredicto. Reevalúa, ajusta, continúa. Este es el método Capricornio, y funciona.",
    "La estructura crea libertad. Los sistemas que construyes hoy son las cosas que te dan espacio mañana — invierte el tiempo.",
    "Tu paciencia es extraordinaria por cualquier estándar. Hoy se está ejerciendo en una situación que genuinamente la recompensa — mantén tu posición.",
    "Un movimiento de carrera u oportunidad profesional está lista para ser considerada seriamente. Reúne la información, haz los cálculos, y confía en tus conclusiones.",
    "El hogar y la fundación te importan, y algo de los tuyos está listo para atención — ya sea literalmente o en términos de las relaciones que lo constituyen.",
    "El reconocimiento por algo que has construido durante un largo tiempo está en camino. Has estado demasiado cerca de ello para ver la magnitud de lo que has creado.",
    "La energía del signo de tierra fundamenta todo hoy. Tu naturaleza práctica es exactamente la fuerza estabilizadora que una situación caótica necesita.",
    "El descanso no es una recompensa para cuando el trabajo esté hecho — el trabajo nunca está hecho. El descanso es mantenimiento. Prográmalo.",
    "Tu brújula interior hacia lo que es real y lo que no es confiable. Cuando algo se siente hueco o performativo hoy, confía en esa lectura.",
    "Un sueño que solía sentirse imposible está comenzando a parecerse más a un plan. La diferencia es que ahora puedes ver los pasos.",
    "La integridad en las cosas pequeñas — cumplir un compromiso menor, ser preciso con un pequeño detalle — se convierte en una reputación que abre grandes puertas.",
    "La visión a largo plazo es tu perspectiva natural. Lo que parece urgente hoy será irrelevante en cinco años. Lo que haces silenciosamente hoy importará en veinte.",
  ],

  Aquarius: [
    "Tu mente se mueve de manera diferente a las personas a tu alrededor, Acuario, y hoy esa diferencia resuelve algo que nadie más veía venir.",
    "Una causa o comunidad que te importa está pidiendo tu participación. Tu visión de lo que es posible es necesaria — no la contengas.",
    "La innovación es tu lenguaje natural. El problema de hoy tiene una solución que nadie ha intentado todavía — y estás en una posición única para verla.",
    "Urano, tu planeta regente, enciende lo inesperado hoy. Algo te sorprende — y la sorpresa resulta ser exactamente lo que necesitabas.",
    "La independencia es no negociable para ti, y hoy se está respetando. Una situación que podría haber sido restrictiva en cambio te deja espacio.",
    "Tu idealismo es una fortaleza, no una ingenuidad. El mundo que imaginas vale la pena trabajar hacia él — sostén la visión y da un paso en su dirección.",
    "Una conversación intelectual hoy va a un lugar inesperadamente profundo. Aprendes algo — o enseñas algo — que permanece en ambos.",
    "El futuro llega en destellos para ti antes de que llegue a otros. ¿Qué patrón estás viendo que otros aún no han nombrado?",
    "La comunidad es donde tus dones se multiplican. Un grupo, una red, un movimiento se beneficia de tu perspectiva hoy — preséntate por ello.",
    "La excentricidad es solo innovación que aún no ha sido validada. No te normalices para entornos que no valen la pena.",
    "Una amistad que ha estado dormida está lista para ser revivida. Las conexiones de Acuario tienen una calidad de atemporalidad — comunícate sin disculparte por el tiempo transcurrido.",
    "La tecnología, los sistemas, o las estructuras que podrían funcionar mejor están captando tu atención. Tu perspectiva sobre cómo mejorarlos vale la pena compartir.",
    "El camino convencional nunca fue tu camino. El desvío de hoy es en realidad la ruta — confía en donde tus instintos se están divergiendo de la dirección esperada.",
    "La objetividad es una de tus mayores fortalezas, pero hoy equilibrala con sentimiento. Las soluciones más innovadoras también consideran la dimensión humana.",
    "Alguien te malentiende hoy, y en realidad no te molesta particularmente — lo cual es en sí mismo una especie de libertad. Déjalo pasar.",
    "Tu visión de algo es más grande que la conversación actual sobre ello. Trae el marco más grande — ayuda a todos a pensar con más claridad.",
    "Un impulso humanitario te pide actuar hoy — no con grandes gestos, sino con una cosa específica y práctica que ayuda a alguien real.",
    "El progreso es tu deseo nativo, y hoy puedes verlo ocurrir en una situación que has estado observando cuidadosamente. Algo está genuinamente mejorando.",
    "La rebelión es útil cuando tiene principios. Hoy, asegúrate de que lo que estás rechazando merece la energía, no solo la resistencia habitual.",
    "Una idea inusual con la que has estado sentado es más práctica de lo que parecía al principio. Discútela con alguien que hace buenas preguntas.",
    "Tu amistad es inusual — independiente, estimulante, no siempre predecible. Hoy alguien valora exactamente esa cualidad en ti.",
    "Un esfuerzo colectivo se beneficia de tu capacidad de ver el sistema en lugar de solo tu parte de él. Ofrece la vista desde las alturas.",
    "La lógica y la intuición no son opuestos — tus mejores perspectivas usan ambas. Hoy lo racional y lo instintivo llegan al mismo lugar desde diferentes direcciones.",
    "La libertad es un valor que vale la pena examinar: ¿libre para hacer qué, exactamente? Hoy, sé específico sobre lo que tu independencia está realmente al servicio de.",
    "El status quo rara vez es incorrecto porque sea verdad — es incorrecto porque dejó de ser examinado. Tu cuestionamiento es valioso incluso cuando es inconveniente.",
    "La energía social es alta hoy pero mantén algo en reserva. Te recargas solo incluso cuando amas a las personas — protege el tiempo que hace eso posible.",
    "Una perspectiva repentina llega hoy — sobre ti mismo, una situación, o una persona — que reenmarca algo que pensabas que ya habías entendido.",
    "Tu originalidad es tu contribución. El mundo tiene suficientes personas que encajan perfectamente en categorías establecidas — tu categoría te necesita en ella.",
    "El cambio no te asusta de la manera que asusta a otros. Algo que cambia hoy que otros encuentran inquietante es simplemente interesante para ti — y tu estabilidad ayuda a quienes te rodean.",
    "La visión que llevas de un mundo mejor no es ingenuidad — es navegación. Sigue caminando hacia ella. La distancia es más corta de lo que parecía cuando empezaste.",
  ],

  Pisces: [
    "Tu sensibilidad es un instrumento finamente sintonizado hoy, Piscis. Lo que percibes en la quietud — en un tono de voz, un destello de sentimiento, un sueño a medio recordar — vale la pena confiar.",
    "La compasión fluye de ti hoy sin esfuerzo. Déjala — no estás perdiendo energía cuando la das desde este lugar, estás expresando de lo que estás hecho.",
    "Un trabajo creativo que se ha estado formando en el fondo está listo para salir. Dale tiempo hoy — incluso treinta minutos en un espacio tranquilo — y ve qué surge.",
    "Neptuno, tu planeta regente, disuelve los límites entre lo interior y lo exterior hoy. Presta atención a las sincronicidades — no son coincidencias.",
    "Tu imaginación es un activo, no una escotilla de escape. Usada activamente, genera las soluciones más hermosas. Usada pasivamente, te aleja de lo real. Hoy, úsala activamente.",
    "Algo o alguien del pasado regresa a tu conciencia — no para retenerte, sino para completar algo que necesita completarse antes de que puedas seguir adelante.",
    "La música, el agua, el arte, o cualquier cosa que evita la mente racional y habla directamente a tu alma es lo que necesitas hoy. Encuéntralo.",
    "Tu empatía te permite sentir lo que otros están pasando con una precisión inusual. Hoy, deja que esa capacidad guíe una amabilidad que aterriza exactamente bien.",
    "La línea entre tus sentimientos y los sentimientos de otros es borrosa para ti — siempre ha sido así. Hoy, comprueba suavemente: ¿cuáles de estas emociones son realmente tuyas?",
    "Una práctica espiritual o momento de quietud hoy te da acceso a un tipo de conocimiento que el análisis no tiene. Lo que llega en el silencio es real.",
    "Tus sueños de anoche tenían algo que decir. Aunque los detalles sean vagos, el sentimiento que dejaron tiene información — quédate con él.",
    "La expresión artística es tu medicina. Algo que ha estado acumulándose emocionalmente encuentra su canal correcto hoy en hacer — escribir, dibujar, tocar, bailar.",
    "La persona en tu vida que más está luchando ahora mismo se beneficiaría de tu presencia más que de tus palabras. Simplemente estar allí, con atención y sin agenda, es profundo.",
    "El idealismo sobre una relación o situación puede necesitar una verificación de realidad suave hoy — no para destruir el sueño, sino para ayudarlo a sobrevivir el contacto con el mundo real.",
    "Tus límites valen la pena clarificar hoy — amablemente pero específicamente. Das tan libremente que las personas a veces toman sin darse cuenta. Esta es una corrección suave, no un rechazo.",
    "Un proceso de sanación que ha estado en marcha — uno que quizás no hayas nombrado conscientemente — está más avanzado de lo que sabes. Algo tierno se está volviendo más fuerte.",
    "La soledad te restaura de maneras que la mayoría de las personas no requieren ni entienden. Toma el tiempo que necesitas sin disculparte por ello.",
    "Un acto de perdón — hacia alguien, o hacia ti mismo — se vuelve posible hoy. No requiere una conversación; simplemente requiere una elección interna.",
    "Tu intuición es tu sistema de navegación más confiable. Un argumento lógico puede ser persuasivo, pero ¿qué sabe tu cuerpo sobre esta decisión?",
    "La belleza en este día está disponible si te desacelas lo suficiente para recibirla. La energía de Piscis sobresale en ser conmovida — déjate conmover.",
    "La verdad emocional de alguien es más visible para ti hoy que para cualquiera a su alrededor. Usa esa percepción suave y sabiamente.",
    "Una fantasía o anhelo que ha estado sentado silenciosamente merece un examen honesto: ¿es esto algo hacia lo que moverse, o algo para liberar? Ambas respuestas están bien.",
    "Tu sentido fluido de ti mismo es un activo en entornos que requieren adaptabilidad. Hoy, encajas en un espacio que sería incómodo para la mayoría — y prosperas allí.",
    "El agua te sana — literalmente. Una ducha tomada lentamente, un paseo cerca del agua, lluvia escuchada desde adentros — cualquiera de estas restablece algo en ti.",
    "Una conexión hecha hoy tiene una calidad de profundidad y reconocimiento que rara vez has experimentado. No dejes que el momento pase sin reconocerlo.",
    "El sacrificio y el martirio son cosas diferentes. El sacrificio es elegido y significativo; el martirio es resentimiento disfrazado. Hoy, sabe en cuál estás.",
    "Tu sensibilidad a la atmósfera es aguda hoy. Un entorno que se siente mal será difícil para trabajar — si puedes cambiarlo, hazlo.",
    "Lo espiritual y lo práctico no están separados en tu vida — se informan mutuamente. Una decisión práctica tomada desde valores espirituales hoy tiene una calidad diferente.",
    "Eres más capaz de manejar el mundo real de lo que a veces crees. Hoy ofrece evidencia suave de eso.",
    "Al final de este día, descansa en el conocimiento de que simplemente estar abierto a la belleza, a los demás, y a las dimensiones invisibles de la experiencia es en sí mismo una especie de contribución.",
  ],
};

export default FORTUNES_ES;
