export interface CompatPair {
  score: number; // 1–10
  summary: string;
  description: string;
}

/** Canonical key order: alphabetically first sign listed first */
const PAIRS: Record<string, CompatPair> = {
  "Aries-Aries": { score: 8, summary: "Blazing mirror", description: "Two Aries together create an electrifying, high-energy partnership. Both are bold and spontaneous, making every day feel like an adventure. The challenge is managing two strong egos — but when they're aligned, there's nothing they can't conquer together." },
  "Aries-Taurus": { score: 4, summary: "Friction of pace", description: "Aries charges ahead while Taurus prefers to dig in and wait. Their natural rhythms clash — Aries finds Taurus slow, Taurus finds Aries reckless. Mutual respect takes real work, but once established they balance each other beautifully." },
  "Aries-Gemini": { score: 8, summary: "Sparkling chemistry", description: "Aries and Gemini both love novelty and move at full speed. Gemini feeds Aries with fresh ideas; Aries gives Gemini the push to act on them. This pairing thrives on constant stimulation and never runs out of things to do together." },
  "Aries-Cancer": { score: 4, summary: "Heart vs. charge", description: "Aries leads with assertive action; Cancer leads with emotion and intuition. Cancer can feel steamrolled by Aries' directness, while Aries finds Cancer's mood shifts exhausting. With patience and tenderness from Aries, this pairing can grow into something meaningful." },
  "Aries-Leo": { score: 9, summary: "Dynamic power couple", description: "Two Fire signs radiating confidence and passion — this pairing lights up any room. Both love grand gestures, excitement, and being seen. The only friction comes from competing for the spotlight, but their shared warmth and generosity usually win out." },
  "Aries-Virgo": { score: 4, summary: "Impulse meets method", description: "Aries acts first and asks questions later; Virgo plans meticulously before moving. Virgo's critiques can sting Aries, who doesn't slow down for analysis. This pairing works best when they treat each other's style as complementary, not a threat." },
  "Aries-Libra": { score: 7, summary: "Opposites attract", description: "Aries and Libra sit directly across the zodiac, creating a magnetic pull of opposites. Aries brings decisiveness; Libra brings harmony and grace. The attraction is real, but compromise is essential — Aries must learn to consult, Libra to commit." },
  "Aries-Scorpio": { score: 5, summary: "Intense but combustible", description: "Both are ruled by Mars, giving this pairing raw power and drive. Scorpio's depth fascinates Aries; Aries' directness both attracts and frustrates Scorpio. Power struggles are common, but when they channel their energy together they become unstoppable." },
  "Aries-Sagittarius": { score: 9, summary: "Adventure without limits", description: "Two Fire signs who live for the thrill — this pairing is pure freedom and fun. Both crave adventure, new experiences, and big ideas, and neither tries to cage the other. Their connection feels effortless, expansive, and full of genuine enthusiasm for life." },
  "Aries-Capricorn": { score: 4, summary: "Impulse vs. strategy", description: "Aries wants it now; Capricorn wants it right. Capricorn's slow, calculated approach frustrates Aries' need for speed, while Capricorn sees Aries as impractical. When their ambitions align, however, they can build something remarkable together." },
  "Aries-Aquarius": { score: 8, summary: "Rebels with shared fire", description: "Both Aries and Aquarius love doing things their own way and hate being told no. Aquarius sparks Aries' mind with visionary ideas; Aries gets Aquarius to stop theorizing and start acting. Together they push each other toward bolder, more original paths." },
  "Aries-Pisces": { score: 5, summary: "Bold meets gentle", description: "Aries is a warrior; Pisces is a dreamer. Aries can sweep Pisces off their feet, but may not slow down long enough to nurture the connection. With care, Pisces softens Aries' edges and Aries gives Pisces the courage to pursue their dreams." },

  "Taurus-Taurus": { score: 7, summary: "Rock-solid comfort", description: "Two Taureans together build the ultimate sanctuary — stable, sensual, and deeply loyal. They understand each other's need for security and indulgence without explanation. The risk is getting too comfortable and resisting necessary change." },
  "Taurus-Gemini": { score: 4, summary: "Steady meets restless", description: "Taurus craves consistency; Gemini craves variety. Gemini's flightiness unsettles Taurus, who needs to know where things stand. If Gemini can commit more and Taurus can loosen up, they can learn a great deal from each other." },
  "Taurus-Cancer": { score: 8, summary: "Nurturing sanctuary", description: "Both Taurus and Cancer crave security, comfort, and deep emotional roots. They build homes, traditions, and lasting bonds with equal devotion. This pairing feels like a safe harbour — warm, loyal, and quietly profound." },
  "Taurus-Leo": { score: 5, summary: "Two stubborn hearts", description: "Both are Fixed signs who rarely budge once their minds are made up. Leo wants admiration and excitement; Taurus wants stability and peace. When they stop locking horns, their shared love of luxury and loyalty creates real chemistry." },
  "Taurus-Virgo": { score: 9, summary: "Earth-sign harmony", description: "Taurus and Virgo are one of the zodiac's most naturally compatible pairings. Both are practical, reliable, and value quality over flash. They build trust slowly and deliberately, creating a partnership that gets stronger year after year." },
  "Taurus-Libra": { score: 5, summary: "Venus-ruled beauty", description: "Both signs are ruled by Venus, giving them a shared love of beauty, art, and refinement. But Taurus needs deep commitment while Libra weighs every option endlessly. If Libra can decide and Taurus can be patient, this becomes a graceful connection." },
  "Taurus-Scorpio": { score: 8, summary: "Magnetic and intense", description: "These zodiac opposites are magnetically drawn to each other. Taurus offers steadiness and sensuality; Scorpio offers depth and transformative passion. Trust comes slowly, but once established this bond becomes one of the most enduring in the zodiac." },
  "Taurus-Sagittarius": { score: 4, summary: "Roots vs. wings", description: "Taurus wants to stay and build; Sagittarius wants to explore and expand. Sagittarius' need for freedom feels threatening to security-loving Taurus. This pairing requires enormous compromise, but each can genuinely broaden the other's world." },
  "Taurus-Capricorn": { score: 9, summary: "Built to last", description: "Two Earth signs who share ambition, practicality, and a long-term view — this is one of the zodiac's most enduring combinations. They understand each other's drive without needing to explain it. Together they build security that stands the test of time." },
  "Taurus-Aquarius": { score: 4, summary: "Tradition vs. revolution", description: "Taurus anchors everything in tradition; Aquarius questions every tradition. Taurus finds Aquarius unpredictable; Aquarius finds Taurus too rigid. With genuine curiosity about each other, they can be surprisingly and productively complementary." },
  "Taurus-Pisces": { score: 7, summary: "Gentle and devoted", description: "Taurus provides the stability Pisces needs to feel safe to dream; Pisces brings poetry and depth to Taurus' world. They share a love of sensory beauty and are both deeply loyal once committed. A quietly beautiful pairing." },

  "Gemini-Gemini": { score: 7, summary: "Electric double act", description: "Two Geminis together is one long, thrilling conversation that never quite reaches a conclusion. They understand each other's restlessness and love of ideas. The risk is that nothing settles — but the sheer vitality and wit of this pairing is unmatched." },
  "Gemini-Cancer": { score: 5, summary: "Mind meets heart", description: "Gemini lives in the intellect; Cancer lives in the feelings. Cancer wants emotional depth and security; Gemini wants variety and lightness. They intrigue each other deeply, but bridging head and heart takes real effort and patience from both." },
  "Gemini-Leo": { score: 8, summary: "Dazzling spotlight pair", description: "Gemini and Leo together are magnetic — witty, warm, and utterly entertaining. Leo brings drama and generosity; Gemini brings ideas and levity. They feed each other's love of fun and social connection, making every gathering better." },
  "Gemini-Virgo": { score: 5, summary: "Sharp minds, different styles", description: "Both ruled by Mercury and razor-sharp communicators, but their styles clash. Virgo is precise and critical; Gemini is free-ranging and improvised. If they can appreciate each other's intelligence rather than compete, the conversation never ends." },
  "Gemini-Libra": { score: 9, summary: "Air-sign perfection", description: "Gemini and Libra are one of the zodiac's most naturally harmonious pairs. Both love ideas, beauty, and elegant conversation. They rarely feel misunderstood — this connection is light, free, and deeply enjoyable." },
  "Gemini-Scorpio": { score: 4, summary: "Surface vs. depth", description: "Gemini skims the surface with quick wit and easy charm; Scorpio dives into the darkest depths. Scorpio finds Gemini shallow; Gemini finds Scorpio suffocatingly intense. A fascinating but often frustrating combination requiring extraordinary mutual respect." },
  "Gemini-Sagittarius": { score: 7, summary: "Curious opposites", description: "These opposite signs share a love of learning, travel, and big ideas. Gemini explores the details; Sagittarius sees the big picture. Their relationship is a constant exchange of perspectives that keeps both intellectually alive and stimulated." },
  "Gemini-Capricorn": { score: 4, summary: "Playful vs. purposeful", description: "Gemini approaches life as an adventure to explore; Capricorn approaches it as a mountain to climb. Capricorn can seem too serious for Gemini; Gemini can seem too scattered for Capricorn. Their differences are real, but so is the potential for growth." },
  "Gemini-Aquarius": { score: 9, summary: "Minds in orbit", description: "Two Air signs who love nothing more than a breakthrough idea — this pairing crackles with intellectual energy. They give each other freedom, stimulation, and the rare feeling of being truly understood. A genuinely exhilarating connection." },
  "Gemini-Pisces": { score: 5, summary: "Dreamers, different wavelengths", description: "Both are Mutable signs — adaptable and imaginative — but they occupy very different inner worlds. Gemini's logic clashes with Pisces' intuition; Pisces finds Gemini flippant about things that feel sacred. Magic awaits if they bridge the gap." },

  "Cancer-Cancer": { score: 8, summary: "Deep emotional home", description: "Two Cancers together create a deeply nurturing and emotionally rich bond. They understand each other's sensitivities without explanation and build a home that feels like a true sanctuary. The risk is amplifying each other's anxieties — they must venture outward together." },
  "Cancer-Leo": { score: 5, summary: "Warmth seeking warmth", description: "Both Cancer and Leo are devoted and big-hearted, but they give and receive love differently. Leo wants admiration and external recognition; Cancer wants intimate emotional security. When each feels truly seen by the other, a genuinely warm bond forms." },
  "Cancer-Virgo": { score: 8, summary: "Devoted and grounded", description: "Cancer brings emotional warmth; Virgo brings practical care — both deeply devoted to those they love. They build a relationship through acts of service, loyalty, and genuine attention to each other's needs. One of the zodiac's most quietly solid pairings." },
  "Cancer-Libra": { score: 4, summary: "Longing for balance", description: "Cancer needs deep emotional intimacy; Libra needs social harmony and mental connection. Cancer may feel Libra is emotionally distant; Libra may feel overwhelmed by Cancer's intensity. Both want peace, but they seek it in very different places." },
  "Cancer-Scorpio": { score: 9, summary: "Soul-deep connection", description: "Cancer and Scorpio are perhaps the most emotionally connected pairing in the entire zodiac. Both Water signs feel deeply and guard their hearts fiercely — but with each other, those walls come down. This bond can be transformative, healing, and lifelong." },
  "Cancer-Sagittarius": { score: 4, summary: "Home vs. horizon", description: "Cancer wants to nest and build roots; Sagittarius wants to roam and explore. Sagittarius' love of freedom can feel like abandonment to Cancer; Cancer's closeness can feel like a cage to Sagittarius. Profound communication and respect are required." },
  "Cancer-Capricorn": { score: 7, summary: "Opposite pillars of strength", description: "Cancer and Capricorn are zodiac opposites who share a deep drive to build something lasting. Cancer provides emotional warmth and intuition; Capricorn provides structure and ambition. Together they form a complementary foundation — a true power couple." },
  "Cancer-Aquarius": { score: 3, summary: "Worlds apart", description: "Cancer lives in the realm of emotion, home, and deep personal bonds; Aquarius lives in ideas, humanity, and intellectual independence. Cancer can feel unimportant to the detached Aquarian; Aquarius can feel smothered. This is the zodiac's most challenging pairing." },
  "Cancer-Pisces": { score: 9, summary: "Ocean of feeling", description: "Two Water signs who dive into the depths together without hesitation. Cancer and Pisces share emotional sensitivity, intuition, and a desire for meaningful connection. They create a world of their own — safe, dreamy, and profoundly loving." },

  "Leo-Leo": { score: 7, summary: "Roaring royalty", description: "Two Leos together command any room they enter. Both generous, dramatic, and warm, they understand each other's need to shine. The challenge is making room for two suns — but with enough mutual admiration, they become a truly spectacular duo." },
  "Leo-Virgo": { score: 4, summary: "Grand vs. precise", description: "Leo loves the big picture and grand gestures; Virgo lives in careful details and practical improvements. Virgo's critiques can deflate Leo's pride; Leo's impracticality can frustrate Virgo. Mutual respect for each other's gifts transforms friction into balance." },
  "Leo-Libra": { score: 9, summary: "Glamorous harmony", description: "Leo and Libra both adore beauty, romance, and social connection, making this one of the zodiac's most naturally delightful pairings. Leo brings warmth and drama; Libra brings elegance and diplomacy. Together they are charming, creative, and deeply loyal." },
  "Leo-Scorpio": { score: 5, summary: "Power and passion", description: "Leo and Scorpio are both intensely powerful and neither backs down easily. The attraction is magnetic, but so is the potential for control battles. If they direct their energy toward shared goals rather than dominance, this becomes one of the most potent pairings." },
  "Leo-Sagittarius": { score: 9, summary: "Fire and freedom", description: "Leo and Sagittarius together is pure exuberance — bold, generous, and alive with possibility. Both love adventure, fun, and inspiring others. Leo gives Sagittarius loyalty and warmth; Sagittarius gives Leo new horizons to explore. An utterly joyful combination." },
  "Leo-Capricorn": { score: 4, summary: "Spotlight vs. long game", description: "Both Leo and Capricorn are ambitious, but Leo wants recognition now while Capricorn plays the long game patiently. Capricorn can seem cold to warm-hearted Leo; Leo can seem flashy to pragmatic Capricorn. Their shared drive for success eventually bridges the gap." },
  "Leo-Aquarius": { score: 7, summary: "Star and visionary", description: "Leo and Aquarius sit opposite each other in the zodiac, creating a fascinating push-pull. Leo is personal, dramatic, and loving; Aquarius is universal, detached, and innovative. The attraction is electric, and each expands the other's world significantly." },
  "Leo-Pisces": { score: 4, summary: "Sun and sea", description: "Leo's fire and Pisces' water can inspire or extinguish each other. Leo wants to be seen and celebrated; Pisces wants to merge and dissolve. Leo may find Pisces elusive; Pisces may find Leo too demanding. Yet the creative potential between them is remarkable." },

  "Virgo-Virgo": { score: 7, summary: "Precision partnership", description: "Two Virgos together build the most efficient, thoughtful, and considerate partnership in the zodiac. They understand each other's attention to detail and desire to improve. The risk is getting lost in criticism or perfectionism — letting good enough be good enough." },
  "Virgo-Libra": { score: 5, summary: "Detail meets balance", description: "Virgo focuses on what can be improved; Libra focuses on what is beautiful and harmonious. Virgo can find Libra indecisive; Libra can find Virgo too critical. Their shared appreciation for refinement and thoughtfulness creates genuine common ground." },
  "Virgo-Scorpio": { score: 8, summary: "Analytical intensity", description: "Virgo and Scorpio are both highly perceptive and neither misses a detail. Virgo provides order and method; Scorpio provides depth and transformative insight. This pairing works in silence as much as in conversation — they read each other with uncanny accuracy." },
  "Virgo-Sagittarius": { score: 4, summary: "Details vs. big picture", description: "Virgo wants to perfect every detail; Sagittarius wants to skip to the grand vision. Sagittarius finds Virgo too cautious; Virgo finds Sagittarius too reckless. But when they collaborate, Virgo's precision grounds Sagittarius' vision into something real." },
  "Virgo-Capricorn": { score: 9, summary: "Earth-sign excellence", description: "Virgo and Capricorn are one of the most compatible pairings in astrology — both practical, reliable, and devoted to doing things right. They build with patience and care, and their trust grows steadily and surely. An extraordinarily solid foundation." },
  "Virgo-Aquarius": { score: 4, summary: "Logic at cross-purposes", description: "Both are analytical, but Virgo's logic is grounded and detail-oriented while Aquarius' is abstract and visionary. Aquarius finds Virgo too narrow; Virgo finds Aquarius too impractical. Yet their combined intelligence can be genuinely formidable if they collaborate." },
  "Virgo-Pisces": { score: 7, summary: "Healing opposites", description: "Virgo and Pisces are zodiac opposites who offer each other exactly what they lack. Virgo provides structure and clarity to dreamy Pisces; Pisces offers spiritual depth and compassion to analytical Virgo. Together they become each other's most devoted healers." },

  "Libra-Libra": { score: 7, summary: "Mirror of grace", description: "Two Libras together create a relationship of extraordinary elegance and mutual consideration. They understand each other's need for balance and beauty without explanation. The challenge is that two indecisive people can find it hard to commit to anything at all." },
  "Libra-Scorpio": { score: 5, summary: "Charm meets depth", description: "Libra floats on the surface with grace and diplomacy; Scorpio plunges into the depths with intensity. Scorpio wants Libra to go deeper; Libra wants Scorpio to lighten up. When they meet in the middle, something genuinely magnetic is created." },
  "Libra-Sagittarius": { score: 8, summary: "Freedom and philosophy", description: "Libra and Sagittarius share a love of ideas, social connection, and the pursuit of something greater. Both are idealistic and generous, inspiring each other to think bigger. This pairing is intellectually alive, socially vibrant, and endlessly engaging." },
  "Libra-Capricorn": { score: 4, summary: "Ideals meet pragmatism", description: "Libra pursues beauty, fairness, and harmony; Capricorn pursues results, structure, and achievement. Capricorn finds Libra indecisive; Libra finds Capricorn cold. Both value integrity, and if they align their ambitions, they can accomplish a great deal together." },
  "Libra-Aquarius": { score: 9, summary: "Intellectual paradise", description: "Libra and Aquarius are one of the zodiac's most harmonious Air sign pairings. Both love ideas, social causes, and meaningful connection. They give each other freedom, stimulation, and profound understanding — the conversation feels like it's been going on forever." },
  "Libra-Pisces": { score: 6, summary: "Beauty and dream", description: "Libra and Pisces both seek beauty — Libra through form and balance, Pisces through feeling and imagination. They can share a dreamy, romantic connection built on art, compassion, and sensitivity. The challenge is that neither is particularly strong at making decisions." },

  "Scorpio-Scorpio": { score: 8, summary: "Volcanic depth", description: "Two Scorpios together is an experience unlike any other — an all-or-nothing fusion of passion, loyalty, and psychological intensity. They understand each other at a level no one else can reach. At their best, this bond is unbreakable. At their worst, it is volcanic." },
  "Scorpio-Sagittarius": { score: 4, summary: "Mystery vs. openness", description: "Scorpio guards everything; Sagittarius shares everything. Scorpio needs loyalty and depth; Sagittarius needs freedom and space. Sagittarius finds Scorpio controlling; Scorpio finds Sagittarius superficial. But the attraction is real, and so is the potential for growth." },
  "Scorpio-Capricorn": { score: 8, summary: "Power and endurance", description: "Scorpio and Capricorn are both driven, strategic, and deeply private. They share an understanding of power, ambition, and the patience required for long-term goals. This pairing is quietly formidable — loyal, disciplined, and built to outlast anything." },
  "Scorpio-Aquarius": { score: 4, summary: "Fixed and frozen", description: "Two Fixed signs who both refuse to change for anyone — the standoffs between Scorpio and Aquarius can be legendary. Scorpio craves intimacy; Aquarius craves independence. Yet their shared intensity and intelligence can create extraordinary breakthroughs if they ever truly align." },
  "Scorpio-Pisces": { score: 9, summary: "Mystical depth", description: "Scorpio and Pisces are one of the most spiritually profound pairings in the zodiac. Both Water signs feel the unseen, trust the intuitive, and crave deep soul-level connection. Together they create a bond that feels fated — intense, healing, and transformative." },

  "Sagittarius-Sagittarius": { score: 8, summary: "Infinite horizon", description: "Two Sagittarians together is an endless adventure — philosophy, travel, laughter, and big ideas fill every corner of their shared life. They give each other total freedom and trust. The only challenge is that nothing practical ever gets done — too busy living." },
  "Sagittarius-Capricorn": { score: 4, summary: "Explorer vs. builder", description: "Sagittarius wants to see the whole world; Capricorn wants to build something that lasts. Capricorn finds Sagittarius irresponsible; Sagittarius finds Capricorn joyless. Yet when they work together, Sagittarius' vision and Capricorn's execution produce remarkable results." },
  "Sagittarius-Aquarius": { score: 8, summary: "Freedom and vision", description: "Two signs who refuse to be boxed in — Sagittarius and Aquarius together are idealistic, innovative, and endlessly forward-thinking. They give each other space without making the other feel abandoned. This pairing is exhilarating and genuinely inspiring." },
  "Sagittarius-Pisces": { score: 5, summary: "Seekers of meaning", description: "Both Mutable signs on a quest for something beyond the ordinary. Sagittarius seeks philosophical truth; Pisces seeks spiritual transcendence. They inspire each other's idealism but can struggle with practical reality together. Beautiful in theory, challenging to maintain." },

  "Capricorn-Capricorn": { score: 7, summary: "Summit partners", description: "Two Capricorns together build something extraordinary through sheer discipline and mutual respect. They understand each other's drive, their dry humour, and their quiet ambition without any explanation needed. The risk is all work and no play — they must enjoy what they build." },
  "Capricorn-Aquarius": { score: 4, summary: "Structure vs. disruption", description: "Capricorn upholds tradition; Aquarius tears it down to build something better. Capricorn finds Aquarius erratic; Aquarius finds Capricorn suffocatingly conventional. Yet both are deeply committed to making the world better — they just disagree on how." },
  "Capricorn-Pisces": { score: 7, summary: "Dream made real", description: "Capricorn gives Pisces the structure to make dreams come true; Pisces gives Capricorn the imagination to dream bigger. They balance each other beautifully — the practical and the poetic, the ambitious and the inspired. A quietly powerful and complementary pairing." },

  "Aquarius-Aquarius": { score: 8, summary: "Revolutionary minds", description: "Two Aquarians together is a think-tank and a revolution waiting to happen. They give each other total freedom, never try to possess one another, and share a vision for something greater than themselves. Intellectually, this bond is extraordinary." },
  "Aquarius-Pisces": { score: 5, summary: "Idealist and dreamer", description: "Aquarius ideates for humanity; Pisces dreams for the soul. Both are compassionate and non-conformist, but they operate on very different frequencies. Aquarius is logical and cool; Pisces is emotional and warm. When they meet in the middle, something genuinely beautiful is created." },

  "Pisces-Pisces": { score: 8, summary: "Merged in the deep", description: "Two Pisces together create a bond of almost otherworldly sensitivity and mutual understanding. They share the same emotional language and spiritual depth. The risk is losing themselves in each other or in fantasy — but at their best, this love feels genuinely timeless." },
};

const SIGN_ORDER = [
  "Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo",
  "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces",
];

/** Returns the canonical key for a pair regardless of input order */
export function pairKey(a: string, b: string): string {
  const ia = SIGN_ORDER.indexOf(a);
  const ib = SIGN_ORDER.indexOf(b);
  return ia <= ib ? `${a}-${b}` : `${b}-${a}`;
}

export function getCompatibility(signA: string, signB: string): CompatPair | null {
  const key = pairKey(signA, signB);
  return PAIRS[key] ?? null;
}

export { SIGN_ORDER };
